### ISSUE TITLE
cookie file on SYNOLOGY DOCKER

### ISSUE THREAD

**Issue by magefesa** [normen/homebridge-bravia#10]
Hi ! 
I m trying to install this amazing plugin but container stops throwing an error of sonycookie file.
I ve added this parameter on JSON structure: 

"cookiepath":"/home/pi/.homebridge/sonycookie",

The problem is the path inside the container.... the error persists...any help please ?

(on setup there is a description): 
cookiepath file name to store the cookie file to, default "/home/pi/.homebridge/sonycookie.file"

THANKS in advance !!!

**Comment by normen** [comment]
Its a file name, not a folder name. Do NOT create a folder called "sonycookie", that is the FILE name! Also, wehn you get error logs, post them.
