### ISSUE TITLE
[Suggestion] Publish all TVs as external accessories

### ISSUE THREAD

**Issue by MattGerrand** [normen/homebridge-bravia#102]
Hey, great work on this plugin, it's really amazing!

One thing I have noticed is that if you add multiple TVs only one will show up in the remote widget in control centre, and with further investigation this is because HomeKit only expects one TV per bridge. So, just a suggestion, if it's possible to use `API.publishExternalAccessories` instead of `API.registerPlatformAccessories` like other plugins have been (such as homebridge-samsung-tizen or homebridge-harmony) it would solve this issue. Also I know that this would break a few configurations that people already have set up so if this is possible you could add an option in the config like homebridge-harmony did such as `"publishAllTVAsExternalAccessory": true`?

All good if this isn't possible as it isn't a big issue, just sharing my thoughts!

**Comment by normen** [comment]
I see, thanks for the info, very interesting. I don't think I'll get around to doing that any time soon but I'll leave this open as a reminder or of anyone wants to take a shot.

**Comment by SlasherKG** [comment]
I know you said this isn't a high priority, but yours seems to be the only plugin that is working currently that I could find, and it would be great to get both TVs working fully.
If not, is there a way to force the 1st TV to work with the Control Center remote and leave the 2nd one off (I really only need the remote control part for my living room as my bedroom physical remote is always nearby)?

**Comment by normen** [comment]
No there isn't. But a PR is welcome.

**Comment by normen** [comment]
> If not, is there a way to force the 1st TV to work with the Control Center remote and leave the 2nd one off (I really only need the remote control part for my living room as my bedroom physical remote is always nearby)?

For "disabling" or "bypassing" the TV remote functionality the solution suggested in this Issue is probably the only one, I don't see a way to disable homebridges behavior of automatically exposing TV accessories as remotes. What you can always do though is simply set up a second homebridge instance, with the 100 device limit per bridge in HomeKit it makes sense anyway plus you'll see a general performance improvement by splitting the work.

**Comment by normen** [comment]
v2.3 allows publishing select TVs as external accessories

**Comment by normen** [comment]
..but apparently theres more to it.. :) I guess I have to set the external accessory type somewhere.

**Comment by normen** [comment]
Can anyone confirm or deny this works for the multiple TV issue?
