### ISSUE TITLE
Wrong key for PAUSE

### ISSUE THREAD

**Issue by blckshdw** [normen/homebridge-bravia#104]
It looks like the wrong key is being sent for PAUSE.  When I ask Alexa to "Pause the TV" it seems to be sending the key for PLAY.  

From https://pro-bravia.sony.net/develop/integrate/ircc-ip/ircc-codes/index.html
I think it should be sending the value AAAAAgAAAJcAAAAZAw==

**Comment by normen** [comment]
The definition for the key in HomeKit is "play/pause".
