### ISSUE TITLE
Can't get tuner TV channels to show

### ISSUE THREAD

**Issue by SlasherKG** [normen/homebridge-bravia#106]
I know I'm missing something, but I've gone over the example configs and everything multiple times and can't figure it out.
How do you get channels to show up, or at least change to the tuner?
I am using over the air antenna for ATSC channels.

Here is my current config:
`{
        "name": "XBR-65Z9D",
        "ip": "192.168.1.110",
        "tvsource": "tv:dvbt",
        "applications": [
            {
                "title": "Hulu"
            },
            {
                "title": "Netflix"
            },
            {
                "title": "Plex"
            },
            {
                "title": "Prime Video"
            },
            {
                "title": "YouTube"
            }
        ],
        "sources": [
            "extInput:component",
            "extInput:composite",
            "extInput:hdmi",
            "extInput:scart",
            "extInput:widi"
        ]
    }`

**Comment by normen** [comment]
You have to add the right source, usually tv:dvbt for antenna, as written in the manual

**Comment by SlasherKG** [comment]
I added "tvsource": "tv:dvbt" as seen in my config above, do I have to add "tv:dvbt" to the "sources" section as well along side the "extInput" entries?

I can't find any manual other than the main README and the API in your Wiki, do you have a separate link?

Thank you for your hard work on this.

**Comment by normen** [comment]
On Thu Jun 4, 2020 at 7:26 AM CEST, SlasherKG wrote:

> I added "tvsource": "tv:dvbt" as seen in my config above, do I have to add "tv:dvbt" to the "sources" section as well along side the "extInput" entries?
They're basically the same, technially theres no difference in setting a tvsource or adding that same source to the sources list.

> I can't find any manual other than the API in your Wiki, do you have a link?

https://github.com/normen/homebridge-bravia

If you find more information about what to do to get your TV to display channels please add it to the wiki or at least reply here.
