### ISSUE TITLE
Apps with spaces in name not shown

### ISSUE THREAD

**Issue by D1e4Jam1e** [normen/homebridge-bravia#108]
Hi, I've the problem that apps that have spaces in there name are not shown in home-app.
Like 1&1 TV and Steam Link below.

                    "applications": [
                        {
                            "title": "1&1 TV"
                        },
                        {
                            "title": "Netflix"
                        },
                        {
                            "title": "YouTube"
                        },
                        {
                            "title": "Disney+"
                        },
                        {
                            "title": "Lieferando.de"
                        },
                        {
                            "title": "Steam Link"
                        },
                        {
                            "title": "Twitch"
                        }
                    ],

**Comment by normen** [comment]
Well with those names you don't need any really. Just use "steam" and "1&1".

**Comment by D1e4Jam1e** [comment]
Doesn't work. Twitch is also not avaible btw.

**Comment by normen** [comment]
so then "twitch" isn't part of the actual name the TV uses

**Comment by normen** [comment]
Just start with an empty app list and you will see the available apps names in HomeKit.

**Comment by D1e4Jam1e** [comment]
> Just start with an empty app list and you will see the available apps names in HomeKit.

You mean  "applications": [] ?
