### ISSUE TITLE
All works like a charm except.... TV Channel

### ISSUE THREAD

**Issue by magefesa** [normen/homebridge-bravia#11]
Hi ! Finally working perfect. Frome Eve app I can control volume, on-off. But channles does not answer... any ideas please ? 

I  have this setup : 
{
    "platform": "BraviaPlatform",
    "tvs": [
      {
        "name": "TV",
        "ip": "192.168.1.221",
        "tvsource": "tv:dvbs",
        "soundoutput": "speaker",
        "maxchannels": 200,
        "cookiepath":"/root/sonycookie",
        "listapplications": 0,
        "apps":[
          "com.sony.dtv.com.amazon.aiv.eu.com.amazon.ignition.IgnitionActivity"
        ]

      }
    ]
  }

**Comment by normen** [comment]
No, my telepathic debugging senses don't seem to report anything.

**Comment by magefesa** [comment]
Where is The log file?

**Comment by normen** [comment]
Trying to receive something again..... Still nothing.

By the way, I have a piece of string in my hand, can you tell me how long it is?

**Comment by dpyy** [comment]
Pretty sure the string says "I'm a douchebag"
