### ISSUE TITLE
Limiting Channels

### ISSUE THREAD

**Issue by Sammy990** [normen/homebridge-bravia#111]
At the moment, it seems there is no option to limit channels.
When I select dvbt as source, the plugin query for all 300+ channels. Isn‘t it possible to allow selecting only channels you want to be available in HomeKit as an Input?

**Comment by leeraymond78** [comment]
I feel there are too many even only 12 channels in my country

**Comment by normen** [comment]
> Isn‘t it possible to allow selecting only channels you want to be available in HomeKit as an Input?

No, thats not possible. A PR is welcome though.

**Comment by Sammy990** [comment]
That’s sad. I’m not a developer unfortunately. However, maybe you can take a look on the bravia tv os plugin from SeydX. It has the ability to define specific channels. Maybe that helps to speed up bringing this feature in this plugin

**Comment by normen** [comment]
Or you use that plugin if it has the features you want.

> That’s sad. I’m not a developer unfortunately. However, maybe you can take a look on the bravia tv os plugin from SeydX. It has the ability to define specific channels. Maybe that helps to speed up bringing this feature in this plugin
