### ISSUE TITLE
Plugin preventing Homebridge to complete launch/start phase

### ISSUE THREAD

**Issue by Danouchka** [normen/homebridge-bravia#113]
Hello 

As the plugin cannot connect to my Sony TV, all Homebridge is stuck to that point. 
As a result, the other plugins are not loaded. 
Is this a plugin issue, a configuration issue or a homebridge issue ? 

Many thanks for your answers, Dan 

[BraviaPlatform] Error:  Error: connect ENETUNREACH 192.168.1.81:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.1.81',
  port: 80
}

**Comment by normen** [comment]
> Is this a plugin issue, a configuration issue or a homebridge issue ? 
No idea, sounds like you have an old version of the plugin. Way too few information to say anything.

**Comment by Danouchka** [comment]
Hello 

I have installed the plugin last week from homebridge server GUI
I have installed homebridge last week as well
I am running latest raspberry pi os buster on raspberry Pi 4 

Dan

**Comment by Danouchka** [comment]
Hi @normen 
Sounds weird that you closed too soon this ticket ! 
Please could you reopen it ? 

My system is 

- Raspbian GNU/Linux Buster (10)
- Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
- node.js v12.18.2
- npm v6.14.5
- Homebridge v1.1.1 
- homebridge-config-ui-x v4.23.2

The bravia plugin
- homebridge-bravia v2.2.3

**Comment by normen** [comment]
> Sounds weird that you closed too soon this ticket ! 
> Please could you reopen it ? 

Theres nothing to follow up on here. The log output you posted is normal when the TV isn't found but it doesn't halt the boot. Idk whats wrong in your setup but your assessment that a non-connected TV halts the homebridge boot is definitely wrong, in theory as well as in the test runs I just now did again. As this is a bug tracker for this plugin and not a bug tracker for your setup (and not a help forum) this issue is closed.

**Comment by Danouchka** [comment]
Many thanks Normen for your answers !

Please find below my bravia setup.
Is there anything wrong below please ? 

Best, Dan 

"tvs": [
                {
                    "name": "Sony KD-49XG9005",
                    "ip": "192.168.1.81",
                    "serverPort": 6042,
                    "soundoutput": "speaker",
                    "applications": [
                        {
                            "title": "Netflix"
                        },
                        {
                            "title": "YouTube"
                        },
                        {
                            "title": "Prime Video"
                        }
                    ],
                    "sources": [
                        "extInput:hdmi"
                    ]
                }
            ],
            "platform": "BraviaPlatform"

**Comment by normen** [comment]
No idea, syntactically no.
