### ISSUE TITLE
iOS 14  not shown as a TV service

### ISSUE THREAD

**Issue by octavio76** [normen/homebridge-bravia#114]
Hi the Pluging is excellent thanks a lot for this work, i know iOS 14 is in beta phase but I have other TV plugin a and function ok the difference is they are publish all TVs as external accessories.

![IMG_1364](https://user-images.githubusercontent.com/29958843/86516043-238eac00-bde3-11ea-84a4-85b620afd2c4.jpeg)

**Comment by normen** [comment]
> Hi the Pluging is excellent thanks a lot for this work, i know iOS 14 is in beta phase but I have other TV plugin a and function ok the difference is they are publish all TVs as external accessories.

Thanks. Yeah, using external accessories would solve some other problems as well. But as you say it might be its only an issue in the beta. It's new features in both HomeKit and HomeBridge.

**Comment by normen** [comment]
Is this still the case with v2.3 when enabling External Accessory mode?

**Comment by octavio76** [comment]
Hi, the behavior is the same, even though it is already shown as an external accessory, but it comes out as Other not as a Television

 attached images
<img width="800" alt="Captura de Pantalla 2020-07-07 a la(s) 2 48 44 p  m" src="https://user-images.githubusercontent.com/29958843/86835087-3f06ea80-c061-11ea-8d3c-c03b24b63777.png">
![IMG_1374](https://user-images.githubusercontent.com/29958843/86835306-7ffeff00-c061-11ea-8f9c-1110970f6225.jpg)

**Comment by normen** [comment]
Did you create a new TV?
> Hi, the behavior is the same, even though it is already shown as an external accessory, but it comes out as Other not as a Television

**Comment by octavio76** [comment]
Hi, I deleted everything and created it again by installing the plugin again, i did it twice with plugin 2.3.0 and 2.3.1.

**Comment by normen** [comment]
Ok, thanks. I guess I'll have to read up on the functionality.

**Comment by octavio76** [comment]
Hi , update iOS to beta 2 and the problem is solved, thanks a lot.
![7E5D7EE4-7432-4657-8375-0A7F0FE2EFB8](https://user-images.githubusercontent.com/29958843/86914789-81263f80-c0e6-11ea-965e-2fd25c03bb92.jpeg)

**Comment by normen** [comment]
Like in "normal mode"?

**Comment by octavio76** [comment]
Hello I just tried as an external accessory, this night test in normal mode

**Comment by octavio76** [comment]
In normal mode it's fine too
![DD425443-6B0C-44DC-9FAA-D43653EA1D7C](https://user-images.githubusercontent.com/29958843/86969025-b789ac00-c132-11ea-8341-07353a06772b.jpeg)

**Comment by normen** [comment]
Cool, thanks for testing!
