### ISSUE TITLE
How to use new "externalaccessory" option?

### ISSUE THREAD

**Issue by SlasherKG** [normen/homebridge-bravia#115]
Maybe I'm doing it wrong, but I can't get a second TV to show up in the Control Center Remote.
What is the proper syntax for adding this value?
Do you just add `"externalaccessory": true,` to the specific TV?
Do you have to add it to all TVs?
Here is my config, currently just the first TV shows up:
`[
    {
        "name": "XBR-65Z9D",
        "ip": "192.168.1.110",
        "tvsource": "tv:dvbt",
        "applications": [
            {
                "title": "Hulu"
            },
            {
                "title": "Netflix"
            },
            {
                "title": "Plex"
            },
            {
                "title": "Prime Video"
            },
            {
                "title": "YouTube"
            }
        ],
        "sources": [
            "extInput:component",
            "extInput:composite",
            "extInput:hdmi",
            "extInput:scart",
            "extInput:widi"
        ]
    },
    {
        "name": "XBR-55X850B",
        "ip": "192.168.1.111",
        "externalaccessory": true,
        "tvsource": "tv:dvbt",
        "applications": [
            {
                "title": "Hulu"
            },
            {
                "title": "Netflix"
            },
            {
                "title": "Plex"
            },
            {
                "title": "Prime Video"
            },
            {
                "title": "YouTube"
            }
        ],
        "sources": [
            "extInput:component",
            "extInput:composite",
            "extInput:hdmi",
            "extInput:scart",
            "extInput:widi"
        ]
    }
]`

Thank you for any direction.

**Comment by SlasherKG** [comment]
Maybe I'm doing it wrong, but I can't get a second TV to show up in the Control Center Remote.
What is the proper syntax for adding this value?
Do you just add `"externalaccessory": true,` to the specific TV?
Do you have to add it to all TVs?
Here is my config.
Currently just the first TV shows up:
`[
    {
        "name": "XBR-65Z9D",
        "ip": "192.168.1.110",
        "tvsource": "tv:dvbt",
        "applications": [
            {
                "title": "Hulu"
            },
            {
                "title": "Netflix"
            },
            {
                "title": "Plex"
            },
            {
                "title": "Prime Video"
            },
            {
                "title": "YouTube"
            }
        ],
        "sources": [
            "extInput:component",
            "extInput:composite",
            "extInput:hdmi",
            "extInput:scart",
            "extInput:widi"
        ]
    },
    {
        "name": "XBR-55X850B",
        "ip": "192.168.1.111",
        "externalaccessory": true,
        "tvsource": "tv:dvbt",
        "applications": [
            {
                "title": "Hulu"
            },
            {
                "title": "Netflix"
            },
            {
                "title": "Plex"
            },
            {
                "title": "Prime Video"
            },
            {
                "title": "YouTube"
            }
        ],
        "sources": [
            "extInput:component",
            "extInput:composite",
            "extInput:hdmi",
            "extInput:scart",
            "extInput:widi"
        ]
    }
]`

Thank you for any direction.

**Comment by normen** [comment]
Check the log and do what it says, add the new TV as an external accessory.
