### ISSUE TITLE
KDL Issue

### ISSUE THREAD

**Issue by Ledbetter14** [normen/homebridge-bravia#117]
I recently wrote about a timeout issue I had with a KDL model TV. On further investigation I can use a cmd line tool to send a WOL command successfully even when the plugin and homebridge become non responsive, resulting in the homebridge instance becoming functional again. This makes me question my config, maybe I dont have WOL set properly?

  {
    "platform": "BraviaPlatform",
    "tvs": [
      {
        "name": "Living TV",
        "ip": "X.X.X.X",
        "mac":"XX:XX:XX:XX:XX:XX",
        "woladdress": "255.255.255.0",
        "soundoutput": "speaker",
        "tvsource": "tv:dvbt",
        "applications": [
          {"title":"Netflix"},
          {"title":"Plex"}
        ],
        "sources": [
          "extInput:hdmi"
        ]

      }
    ]
  }

Is there anything obvious here?

**Comment by Ledbetter14** [comment]
I have found this error:

15/07/2020, 5:23:10 pm] [BraviaPlatform] Error when sending WOL packets Error: send ENETUNREACH 255.255.255.0:9
    at doSend (dgram.js:681:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:313:12)
    at afterDns (dgram.js:627:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
 {
  errno: -4062,
  code: 'ENETUNREACH',
  syscall: 'send',
  address: '255.255.255.0',
  port: 9
}

Is port 9 a possible conflict? Or is it standard?

**Comment by normen** [comment]
usually you don't need the woladdress but I guess you added it because you had issues in the first place?

**Comment by Ledbetter14** [comment]
Yeah, that’s right. Everything is working except WOL which gives that error. I’m on the latest version of the plugin. Copy pasting everything into y command line tool wakes the TV perfectly.

**Comment by Ledbetter14** [comment]
My TV uses port 80, which I have tried adding into the config but it still uses port 9 in this error.

**Comment by normen** [comment]
Yeah, WOL always works with UDP requests on port 0,7 or 9.

**Comment by ZhxChen** [comment]
Does this plug-in have a function to mute the TV?

**Comment by normen** [comment]
Yes, check the readme

**Comment by ZhxChen** [comment]
> Yes, check the readme
> […](#)
> On Sun Jul 19, 2020 at 4:06 PM CEST, ZhxChen wrote: Does this plug-in have a function to mute the TV? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#117 (comment)](https://github.com/normen/homebridge-bravia/issues/117#issuecomment-660648619)

TV Remote
The TV registers as a TV remote device in HomeKit and allows to use basic function keys and set the volume through the Apple Remote app or iOS configuration screen. Use your phones volume knobs to set the TV volume!

.........................................................................................................................

i want mute  knobs not volume  knobs

**Comment by normen** [comment]
> TV Speaker
> In addition to the iOS remote the plugin also exposes the TV speaker as a HomeKit accessory however only some apps show that accessory type, Apples Home app does not.

**Comment by ZhxChen** [comment]
> > TV Speaker
> > In addition to the iOS remote the plugin also exposes the TV speaker as a HomeKit accessory however only some apps show that accessory type, Apples Home app does not.

Apples Home app is stupid
