### ISSUE TITLE
Doubt -error- "Socket hang up"

### ISSUE THREAD

**Issue by facutopa** [normen/homebridge-bravia#118]
Hi guys, first of all sorry for creating an issue when this is more like an error from my side. 
I want to set up but mabye I making something wrong. 
I researched a lots but I'cant find a solution :(
![Snipaste_2020-07-18_16-01-07](https://user-images.githubusercontent.com/7283431/87859982-f4faf000-c90f-11ea-8a20-f065a832c3ee.jpg)

I seted up the IP of the Android TV but maybe the problem could be the port? 
Thanks and regards!

**Comment by facutopa** [comment]
Sorry, **update 1:**
I just fix the port topic, but now I get the next problem:
![Snipaste_2020-07-18_16-01-07](https://user-images.githubusercontent.com/7283431/87860387-83bd3c00-c913-11ea-8a2d-5e9ad1bc65cd.jpg)

I understand this is not a web of support, but I don't find other place to post this problem, sorry
If you can't help me I will understand, thanks in advance!

**Comment by normen** [comment]
The message basically just said that the connection to the TV was reset. Maybe your TV isn't compatible?

**Comment by facutopa** [comment]
Yes, maybe, I have a TCL Android TV.
No problem! BTW thanks!

**Comment by normen** [comment]
Yes, this is definitely only for Sony TVs, but it works with some Sony TVs that are not running on AndroidTV
