### ISSUE TITLE
Missing TV input options

### ISSUE THREAD

**Issue by Pichiasister** [normen/homebridge-bravia#119]
In `readme`, `tvsource` were defined as `tv:dvbt`, `tv:dvbc` or `tv:dvbs`. While using `avContent.getSourceList({"scheme":"tv"})`, some user might have different value appropriate which depends on various region. For Analog, `tv:analog` is an option. 

Using the UI in Homebridge were unable to choose option other than dvbt/c/s as its has defined in `config.schema.json`. Seems it should be look into?

**Comment by normen** [comment]
Check the manual, just add your string to the input list.
