### ISSUE TITLE
Implementing the homekit speaker standard

### ISSUE THREAD

**Issue by MaxSchouten** [normen/homebridge-bravia#12]
Hi Normen,

Are you planning on implementing the new HomeKit speaker standard in this plugin?
See https://github.com/nfarina/homebridge/issues/1326.

**Comment by normen** [comment]
Hm? It is registered as a HomeKit speaker device. AirPlay2 is for streaming.

**Comment by MaxSchouten** [comment]
It doesn't show up in the iOS 11 home app though...

**Comment by normen** [comment]
Right, exactly as I describe it in the readme.

**Comment by MaxSchouten** [comment]
I see... I was under the impression this referred to the iOS 10 app, rather than 11.

**Comment by normen** [comment]
Well you don't know anything about iOS 11 either because you're using a beta and not the final product.

**Comment by vswraith** [comment]
Is it supposed to work as a speaker in ios11 Home app now?

**Comment by normen** [comment]
Doesn't seem like the Home App or Siri supports speakers other than AirPlay2 speakers in iOS11. HomeKit in general supports them though, you can control them through the other HomeKit apps.
