### ISSUE TITLE
HDMI Inputs randomly disappear from TV in HomeKit 

### ISSUE THREAD

**Issue by basxx2** [normen/homebridge-bravia#120]
Hi, 
I have read through the issues existing here for this plugin already and while some were similar, I think I have a little bit of a different issue. 
My TV is constantly showing in HomeKit so no issue there, however my HDMI inputs randomly disappear. I can‘t seem to find a reproducible logic here. Restarted all devices but most of the times they don’t show up, but sometimes they do without anything changed in the system. 

Have attached two screenshots of both situations. 

Works:
![8C154243-4550-4F81-BBDD-DBA7E2F74BAD](https://user-images.githubusercontent.com/53945090/89122283-569d8b80-d4c6-11ea-90d5-09868c307946.jpeg)

Does not work:
![7B2E44D4-65E7-4A74-9513-1207DB1BB0A1](https://user-images.githubusercontent.com/53945090/89122285-58ffe580-d4c6-11ea-9591-ab64661f75a3.jpeg)

Thanks

**Comment by normen** [comment]
You can try and run the plugin with debug flag set to true (in the main platform entry, where the tvs arrays are)

**Comment by basxx2** [comment]
Did that now. See my config below. 
The Homebridge log does not show any specific entries (at least not more than what it shows without debug). Is there another place I need to check?

        {
            "tvs": [
                {
                    "name": "TV",
                    "ip": "192.168.178.48",
                    "soundoutput": "speaker",
                    "channelupdaterate": false,
                    "debug": true,
                    "sources": [
                        "extinput:hdmi"
                    ]
                }
            ],
            "platform": "BraviaPlatform"
        }

**Comment by normen** [comment]
As said, the "debug" entry needs to be on the same level as the "tvs" and "platform" entry.

**Comment by basxx2** [comment]
Did that now. No change in the log. 

        {
            "platform": "BraviaPlatform",
            "debug": true,
            "tvs": [
                {
                    "name": "TV",
                    "ip": "192.168.178.48",
                    "soundoutput": "speaker",
                    "channelupdaterate": false,
                    "sources": [
                        "extinput:hdmi"
                    ]
                }
            ]
        }

**Comment by normen** [comment]
Idk, maybe your TV only reports the HDMI inputs when the devices are on or something. But maybe if you remove the channelupdaterate entry from your config you'll get them at some point when they're available.

**Comment by basxx2** [comment]
Mmhh I actually added the channelupdaterate only yesterday as I read in other posts that it resolved other issues. The issue was already there before I had it in.

**Comment by normen** [comment]
Just realizing your config has "extinput" instead of "extInput" (capital I)

**Comment by basxx2** [comment]
This did not resolve the issue, list in the TV accessory is still empty and every HDMI input is shown as a separate tile without a function. 

![EC7E83B3-A933-4219-8AD7-477A9B59ADE1](https://user-images.githubusercontent.com/53945090/90288482-439d9a80-de7a-11ea-9809-0a9bc880679d.jpeg)

![796C6911-6A58-42E1-8FFE-7CED758EC2B7](https://user-images.githubusercontent.com/53945090/90288559-68920d80-de7a-11ea-8394-3758609abe8c.jpeg)

**Comment by normen** [comment]
If the HDMI inputs are shown now then this issue is resolved. For the tiles see #74 - just force-quit your Home app once.

**Comment by basxx2** [comment]
As I mentioned in my initial post, it keeps switching back and forth without a reproducible logic. 80% or the cases I have the separate tiles, and sometimes it all works fine. I could not see the force close as workable. My TV accessory stays empty most of the times.

**Comment by normen** [comment]
The log shows (also without debug) when the inputs are added and removed because the TV doesn't report them. With the information you're giving ("It doesn't work" and "I see tiles") I'm afraid theres no logical conclusion to this.
