### ISSUE TITLE
TV needs regular authorization

### ISSUE THREAD

**Issue by DJBenson** [normen/homebridge-bravia#121]
Is there a reason why a TV would need regular authorization, specifically when Homebridge is restarted? I've now split my Homebridge setup into six instances and put homebridge-bravia in an instance which doesn't need restarting so much but this seems an extreme workaround for the average user.

I had no idea until today when my TV told me I could no longer authorize new devices that Homebridge had been taking up new slots each time it has to re-pair with the TV.

Also am I imagining it (or confusing with another plugin) but didn't you used to be able to authenticate with the TV using a cookie? This was far more stable IMO.

EDIT: No, not imagining it, the code still references the cookie option but all reference to it are removed from the instructions for setting up the plugin. Is the cookie method still supported?

**Comment by normen** [comment]
Nothing much changed about that except that the UUID for each TV is unique now. Its stored in the accessory cache, so if you delete that then yes, the TV would have to re-authorize the new UUID. Under normal circumstances that should not be necessary.

**Comment by normen** [comment]
I think you're misunderstanding the purpose of the cookie though, thats for the first connection in basic mode - to initialize the handshake with the UUID, registering that in your TV - after that the cookie isn't really used anymore. 

Edit: It had to be stored on disk as you'd restart the plugin after entering the pin, deleting the cookie data from memory.
