### ISSUE TITLE
PAUSE doesn't work at first try

### ISSUE THREAD

**Issue by mueller-webservice** [normen/homebridge-bravia#122]
When I watch something for a while and then send the PAUSE command, the TV does not respond. It only works if I send it again. It's like it has to be woken up first to work on the second try. This behaviour only appears with PAUSE. When I use volume control or turn the TV on / off, everything works fine. All I can see in the log related to this is following:

`[Alexa] PlaybackController Pause 192.168.178.100 51826 undefined null
`

I trigger the commands via Alexa, which I guess should not make any difference, especially if the other commands work fine. Maybe it is just a setting in the TV but I followed all instruction during install.

**Comment by normen** [comment]
>
> `[Alexa] PlaybackController Pause 192.168.178.100 51826 undefined null
> `
>
> I trigger the commands via Alexa, which I guess should not make any difference, especially if the other commands work fine. Maybe it is just a setting in the TV but I followed all instruction during install.
>

I wouldn't be so sure about that, the error message isn't even from this plugin, indicating that the Alexa plugin has some nullpointer. Did you test your assumption by not using Alexa to press the button?
