### ISSUE TITLE
ECONNREFUSED on install

### ISSUE THREAD

**Issue by distantnative** [normen/homebridge-bravia#123]
I am trying to get this plugin going I have entered the IP address `192.168.1.7` as shown in my router. But on restarting Homebridge I get:

```
 [BraviaPlatform] Error:  Error: connect ECONNREFUSED 192.168.1.7:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.7',
  port: 80
}
```

I assume either the address or the port is wrong. But according to the router, the IP address is correct. And I have no idea how to find out what other port to use. Any clues? Thanks a lot.

**Comment by normen** [comment]
Connrefused means that the host is there but doesn't accept your connection attempt. Could mean many things.
- it's not a compatible Sony TV
- it's using another port instead of 80
- you have to specifically enable remote control in that TV model
- you misidentified the IP
- etc.

**Comment by distantnative** [comment]
@normen any hints on how to find out the port?

**Comment by normen** [comment]
Manual?

**Comment by distantnative** [comment]
Ok, I see this isn't a place that cares about support. Thanks anyways.
