### ISSUE TITLE
iOS 14 GM shows TVs with Home icon not as TV

### ISSUE THREAD

**Issue by mickeyc515** [normen/homebridge-bravia#124]
It’s my understanding that the TV needs to be identified as something different to display correctly as a TV in iOS 14 GM. If I come across the change needed, I’ll add details. 
![220900F6-E8FA-471C-960E-4732332F6920](https://user-images.githubusercontent.com/67304479/93414538-82ef4a80-f86f-11ea-95ac-8070f1f11880.jpeg)

**Comment by dnwilliams78** [comment]
Same issue here.

**Comment by lcshmn** [comment]
see #114 - since iOS14 GM Apple reverted something so TVs need to be published as an external accessory again to display properly.
Try setting "externalaccessory" to true in your configurations - that worked for me!

**Comment by normen** [comment]
Yeah, I also explicitly set the accessory category since v2.3.2 to avoid this but it seems that TVs now *need* to be external accessories to work properly - though except for the icon thing my TV seems to work fine like before.

**Comment by mickeyc515** [comment]
Agree. It seems to work just fine. I did enable external accessory for both my bravias. They still show as a house and only one shows in the remote app. 

Anything specific I need to do?

This is my config now:
`        {
            "tvs": [
                {
                    "name": "Family Room TV",
                    "ip": "192.168.1.73",
                    "externalaccessory": true,
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbt"
                },
                {
                    "name": "Master Bedroom TV",
                    "ip": "192.168.1.127",
                    "externalaccessory": true,
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbt"
                }
            ],
            "platform": "BraviaPlatform"
        }, `

**Comment by lcshmn** [comment]
remove it from your cachedAccessories first
e.g. by temporarly removing the entrys from your config (while keeping the plugin itself installed) and restarting homebridge once.

**Comment by mickeyc515** [comment]
This did the trick. I ended up deleting the entries and setting them back up. Thank you.

**Comment by normen** [comment]
Cool. So it seems externalaccessory should be the default now.. I guess I'll have to push a 2.4 update at some point with externalaccessory as default and some updated docs on adding the TV via the code.

**Comment by normen** [comment]
So as external accessory mode is broken (homebridge doesn't store the TV in its cache) I had to disable it for now, reopening this so ppl find this issue. Any hints on how to make homebridge store external accessories in its cache are very welcome.

**Comment by mickeyc515** [comment]
Yes I realized this issue late in the night. I also realized it as I kept trying to set up my second tv.

**Comment by normen** [comment]
Okay, the latest version has a working external accessory mode, you will have to re-create or rename your TV after enabling it though.

It comes with some caveats, the TV channels are not stored on homebridge reboots, I'd have to create the whole dynamic platform storage stuff myself... or homebridge adds accessory caching for external accessories.

Edit: And again, for me everything works just as before except for the icon.

**Comment by benjaminbogdanovic** [comment]
When you say everything works for you as before, apart from the icon, are you running in "normal" mode, or in external accessory mode?

I am in "normal" mode, and have the icon issue, but everything else is still working post the iOS 14 update. Is there any gain to swapping modes? Apart from the icon potentially? If it ain't broke, don't fix it? 😅

**Comment by normen** [comment]
Yeah, normal mode, thats why I say it. I don't see much of a reason to switch.

**Comment by ryoma3111** [comment]
Same issue

**Comment by Sh0n** [comment]
For me, put externalaccessory to true make disappear my TV from Homekit...wired !

**Comment by normen** [comment]
> For me, put externalaccessory to true make disappear my TV from Homekit...wired !

Well it's an external accessory then, you have to add it manually, as explained in the README

**Comment by Sh0n** [comment]
> > For me, put externalaccessory to true make disappear my TV from Homekit...wired !
> 
> Well it's an external accessory then, you have to add it manually, as explained in the README

Yes sure, but when i scan the code, only bridge is detected, but no TV :(
