### ISSUE TITLE
Need to authenticate with TV!

### ISSUE THREAD

**Issue by diegoweb100** [normen/homebridge-bravia#126]
HI, 

I have 2 TVs so I've set-up both the TVs as externalAccessory. Even if the TV was authenticated correctly the first time, each time that I restart homebridge I need to reenter the pin. I don't know if this is correct or not and if can help Home app Setup code is equal for each TVs.

Any idea? I'm doing something wrong?
<img width="846" alt="Schermata 2020-09-18 alle 08 13 22" src="https://user-images.githubusercontent.com/42244185/93562702-d7391e00-f986-11ea-877e-26efc5f99375.png">
<img width="854" alt="Schermata 2020-09-18 alle 08 05 36" src="https://user-images.githubusercontent.com/42244185/93562513-74e01d80-f986-11ea-80d2-5495aed4ee6d.png">
<img width="1014" alt="Schermata 2020-09-18 alle 08 05 07" src="https://user-images.githubusercontent.com/42244185/93562521-76a9e100-f986-11ea-84db-faf496f0a946.png">

        {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "TV 55",
                    "ip": "192.168.1.14",
                    "externalaccessory": true,
                    "channelupdaterate": "30000",
                    "updaterate": "5000",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbt",
                    "serverPort": "8980",
                    "applications": [
                        {
                            "title": "Netflix"
                        }
                    ]
                },
                {
                    "name": "TV 43",
                    "ip": "192.168.1.16",
                    "externalaccessory": true,
                    "channelupdaterate": "30000",
                    "updaterate": "5000",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbt",
                    "serverPort": "8981",
                    "applications": [
                        {
                            "title": "Netflix"
                        }
                    ]
                }
            ]
        }

**Comment by normen** [comment]
Seems like your homebridge forgets the cached accessories for some reason.

**Comment by normen** [comment]
Meh, actually homebridge doesn't store the external accessory context.. wtf.

**Comment by normen** [comment]
Okay, I disabled external accessory mode for now as its broken, the TV doesn't get stored in the homebridge cache, as soon as I find out how to achieve that I'll add it again - any info is very welcome.

**Comment by diegoweb100** [comment]
Well if it can help,
 homebridge is storing the accessory, in fact after the restart, I had to delete them from the UI in the external accessory sessions (Unpair Bridges / Cameras / TVs / External Accessories) not into the "Remove Single Cached Accessory"

**Comment by normen** [comment]
Well its actually homekit itself that stored that "version" of the device. Anyway, the latest version 2.4.2 has a working external accessory mode but it needs to re-scan the TV channels on each homebridge boot.
