### ISSUE TITLE
TV asks for a pin at each home bridge restart

### ISSUE THREAD

**Issue by Morty72** [normen/homebridge-bravia#127]
Hi,
I installed version 2.4.2 and since, each time I restart homebridge I have to re-enter a pin to be able to control the TV.
Any help is welcome.

**Comment by miljw002** [comment]
This is my first time trying this plugin and I have the same experience. I was wondering it it was me.

**Comment by downloard** [comment]
Same here :(

**Comment by normen** [comment]
Without any info theres no way to help. Do you use external accessory mode? Whats your config? Whats the log output? Etc.

**Comment by normen** [comment]
I actually found an issue that might have caused this, try updating to 2.4.3

**Comment by miljw002** [comment]
I’ve updated to 2.4.3 and it seems to have fixed the issue. Thanks for the quick help.

**Comment by Morty72** [comment]
Hi,
Same for me thank you very much for your quick help. 

Cordialement,

Alexandre BEAUNOM
