### ISSUE TITLE
How to scan more channels

### ISSUE THREAD

**Issue by dcaccount** [normen/homebridge-bravia#131]
Hello,
I have installed the plugin and it is working just fine. Thanks for your great job.

But it looks like it has scanned just 50 channels. How can I add more? I have my remote cams on channel 100.

Then, if need be, how to rescan them?

Last but not least, is there a way to switch it on on a given channel? For instance 100.

Please advise.
Thanks,
Dan

**Comment by normen** [comment]
1) You can only scan the first 50 channels currently, you could move your cameras to lower channel numbers if you need to access them.
2) The channels are rescanned automatically unless you disable that.
3) Yes, with HomeKit automations or scenes. Remember to "wiggle" the channel item once when creating the scene so it's really in the scene, not just the on/off state of the TV.
