### ISSUE TITLE
ERROR: Large endpoint Cookie, removing endpointID => TV

### ISSUE THREAD

**Issue by dastr010** [normen/homebridge-bravia#134]
Hi,

this error message  "ERROR: Large endpoint Cookie, removing endpointID => TV" appears round about every 10 min. in the homebridge log.

Any ideas?

Thanks and regards,
Daniel

**Comment by normen** [comment]
Nope, no idea. My plugin doesn't generate that message.

**Comment by lcshmn** [comment]
@dastr010 FYI the error message is from the [homebridge-alexa](https://github.com/NorthernMan54/homebridge-alexa) plugin if you want to investigate this further...
I get the same error message - but Alexa still recognizes the TV. So if this is causing functional problems for you maybe take a look at the code or report the issue there.

**Comment by normen** [comment]
Maybe it doesn't complain in external accessory mode..
