### ISSUE TITLE
Serial Number

### ISSUE THREAD

**Issue by SalikovAlex** [normen/homebridge-bravia#135]
Add ability to set serial number of accessory. 

I hope it will fix eve home app.

**Comment by normen** [comment]
The serial should be read from the TV instead.

**Comment by SalikovAlex** [comment]
It will be nice.
Because now I have "Default-SerialNumber"

**Comment by SalikovAlex** [comment]
https://github.com/homebridge/homebridge/issues/2503

**Comment by normen** [comment]
Sure, just send a PR
