### ISSUE TITLE
After a while, Siri will probably not find the devices

### ISSUE THREAD

**Issue by michel0271** [normen/homebridge-bravia#136]
Hi, after a period of non-use, it is not possible to switch programs via Siri. Siri doesn't find a couple of devices comes in response. Only when I log back into the Homebridge Dashboard will it work again. Can i do something?

*iOS and Homepod newest iOS, Homebridge V1.2.3 and newest homebridge-bravia

Greetings

**Comment by normen** [comment]
no idea
