### ISSUE TITLE
Device become unresponsive

### ISSUE THREAD

**Issue by diegoweb100** [normen/homebridge-bravia#137]
Hi,

I have a strange issue after the last release that affect only the "Debian" sony TV Version" (I have also an android that is working)..

Let me try to explain... as soon you pair the tv with HomeKit everything working smoothly in to the Home.app but after some days is not possible to change the channel, turn on/of the TV. 

What I observed was that if you leave the TV off (still connected to LAN+ power) and the accessory disappear from Home.app (..the strange thing is that the other tv is still present...) and when try to turn the tv on it does not. if you turn it on using the physical remote the tv reappears on Home.app but, you could not change anymore the sources (or channel even if you wait for the refresh), turn it off or on!All this is not happen immediately but after some days..

i enable the debug and here is what I got...

[10/30/2020, 7:55:15 PM] [BraviaPlatform] Stored channels in external storage
[10/30/2020, 7:55:45 PM] [BraviaPlatform] TypeError: Cannot read property '0' of undefined
    at onSucces (/homebridge/node_modules/homebridge-bravia/index.js:470:34)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-bravia/index.js:922:9)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Another issue...if I try to add composite or other sources all channels are disappearing
                    "tvsource": [
                        "tv:dvbt",
                        "extInput:composite",
                    ],

could you help me whit this two challenge?

thanks a lot!

my config...

        {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "TV 55",
                    "ip": "192.168.1.XXX",
                    "externalaccessory": true,
                    "channelupdaterate": "30000",
                    "updaterate": "5000",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbt",
                    "serverPort": "8980",
                    "debug": true,
                    "applications": [
                        {
                            "title": "Netflix"
                        }
                    ],
                    "sources": [
                        "extInput:hdmi"
                    ]
                },
                {
                    "name": "TV 43",
                    "ip": "192.168.1.YYY",
                    "externalaccessory": true,
                    "channelupdaterate": "30000",
                    "updaterate": "5000",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbt",
                    "serverPort": "8981",
                    "debug": false,
                    "applications": [
                        {
                            "title": "Netflix"
                        }
                    ],
                    "sources": [
                        "extInput:hdmi"
                    ]
                }
            ]
        }

**Comment by normen** [comment]
The error basically just indicates that the TV didn't respond with a proper message. Looks like a networking issue on the TV side.

For your other issue - `tvsource` is not an array, its just an element of the sources array. Add other inputs to the `sources` array instead.
