### ISSUE TITLE
All channels shown as separate "switches", not in input list.

### ISSUE THREAD

**Issue by aivanise** [normen/homebridge-bravia#139]
I have a KL-65W855C and all my channels are shown as some kind of status displays (see a bunch of 'On's at the top of the attached screenshot) and not in the sources list. If I choose to display them as separate tiles, I get a bunch of buttons that all show as 'On' but there is nothing I can do with them except remove them from display.

Tried different channel sources, but the only one that works (i.e. shows any channels)  is Antenna, although the actual source is DVBC, that might also be a symptom of something. Also tried the "External accessory" option, that makes no difference.

![image](https://user-images.githubusercontent.com/3426040/98354878-a473e380-2021-11eb-85de-4872291e4e55.png)

**Comment by normen** [comment]
See #74
