### ISSUE TITLE
Arrange/Sort applications and TV channels in input list and add AndroidTV home screen

### ISSUE THREAD

**Issue by fanfadrian** [normen/homebridge-bravia#141]
Hey normen, thanks for the amazing plugin! I ditched the native Homekit functionality of my A9G because of your amazing work!

I try to figure out if I can list the applications before the TV channels in the input list, but found no solution.
I choose applications like Netflix more often than individual TV channels, but they are located at the bottom of the input list. This results in a long scroll over the 50 TV channels before seeing the applications, sometimes stopping and selecting one channel by mistake. Rearranging the order of applications and tvsource in the config didn't work.

Another thing I try to achieve is to add the Android TV home screen view as an input source. I tried with adding an application called "Home", but it didn't work. Is there a way to achieve this? And if so, would it be also possible that it is the default, or at least the first item in the input list?

Thanks in advance for reading and considering :)

**Comment by normen** [comment]
For the first, maybe try to rearrange them in the Home app on iOS. If you long-press the TV you should be able to open its settings.
For the latter you'd need to specify part of the name of the app as detailed in the manual. Caveat is that the app might not report the same name you see on your TV screen. Check the TV settings if you have some option to "List installed Applications" or something where you might see the "real" name of your TV.

Am 12.11.2020 10:48 schrieb fanfadrian:

**Comment by fanfadrian** [comment]
Thanks for the super fast reply!

If I go to the settings for the TV in HomeKit I can edit the input names, but not rearrange them. I tried long press and dragging them around.

For triggering the home screen of the Android TV interface I looked into the installed apps on my TV and found "Android TV - Startseite" (german for "Android TV - Homescreen", com.google.android.tvlauncher) under system apps. But if I set this string as an application it will not show up in the input list. I also tried "Android TV Home", which is the english name of the app.
The "Android TV Home" system app (com.google.android.tvlauncher) also has no "Open" button in the app information, as e.g. Netflix has. So maybe your plugin doesn't list it as application because of that.

Maybe it would be possible to get around this if you could implement what the "Home" button on the TV remote does, as an input. Then the TV always goes to the home screen, no matter what app or TV channel is open.

**Comment by normen** [comment]
Yeah, if its no regular app it can't be opened through the HTTP command. For the remote buttons that are possible through HomeKit - all of them are implemented really, the remote shows all functions I can put there. Ofc a "IR via HTTP" command could be issued by the plugin but where would you configure and use that in homebridge? As a "fake app" that is added when you add a checkbox? Very ugly and cumbersome to implement for such an edge case so I guess you'll have to live with that.

Theres another bravia plugin (homebridge-bravia-tvos) that has all kinds of hacks like a lamp to control the TV volume and whatnot, maybe that one has some function for that (or the dev is willing to add it).

For the ordering there might actually be a way to enable that, I'm not sure. Really HomeKit does the name editing and saving all by itself right now so theres no code I could change or anything, but maybe theres an option in homebridge I could enable though. But I have no real incentive to look for that to be honest so I wouldn't wait for any progress on that front 😉

Am 12.11.2020 11:31 schrieb fanfadrian:
