### ISSUE TITLE
Add custom ON/OFF direct URL command

### ISSUE THREAD

**Issue by Sh0n** [normen/homebridge-bravia#142]
Hi ! I try to customize your plugin like this :

My goal is to add two new parameters called "onURL" and "offURL" which is direct URL commands.
If one of this parameter is set, plugin call this url to turn ON (or OFF) TV instead of normal command.

For example, i want to call my personal api which turn ON my Apple TV for turn ON my TV.

I tried something [on my repo](https://github.com/Sh0n/homebridge-bravia-extra), but i doesn't for the moment.

**Comment by normen** [comment]
Okay.. I'd recommend simply using CEC and turning on your TV automatically via HDMI though. Or making a scene that turns on both. At any instance this is not something I see fitting to this plugin. I'd suggest simply making a separate app for that. I guess your only real reason to try to do it this way is because this plugin can already communicate with the TV, so you could use some of the code, idk.

Anyway GL with your endeavours.

Cheers,
Normen

Am 14.11.2020 02:18 schrieb Sh0n:

**Comment by Sh0n** [comment]
The advantage for me is to have one and only one device recognized as TV on my home application. 
Thereby, i can mange power, channel and other stuff with this one.

It's only for optimization and WAF upgrade :)

I think i'm not so far  with my fork but i don't know why it won't work for the moment.

In **setPowerState**, i add this line **if** my new argument are set (onURL for example) : 
`this.makeHttpRequest(onError, onSucces, new URL(this.onURL), null, false, true);`
_(onURL is my direct http URL)_

I add one last boolean argument in **makeHttpRequest** which indicate that i want use direct URL :
`function (errcallback, resultcallback, url, post_data, canTurnTvOn, directURL = false) `

and last modification in this function :
`var post_options = directURL ? url : that.getPostOptions(url);`

Other modifications are on config.schema to add onURL and offURL parameters.

Do you see something wrong ?

**Comment by normen** [comment]
No idea, for me what you intend to do and your changes don't fit together, I don't see the point of either and frankly I'm not really too inclined to debug your code.. Especially the code for the TV on check in homebridge-bravia is relatively complicated so you'd really be much better off if you simply listened to that switch in another homebridge plugin through automation.

Anyway good luck and have fun hacking at your home setup - it's fun 🙂

Am 14.11.2020 03:45 schrieb Sh0n:
