### ISSUE TITLE
Sony Bravia disappears after a less seconds

### ISSUE THREAD

**Issue by chrstnkrmr** [normen/homebridge-bravia#143]
Hi,

I added my Sony Bravia TV via Hoobs and Homekit successfully.
After displaying the tile in the HomeKit app it disappeared again and didn‘t come back.

My iPhone runs iOS 14.2, Apple TV also 14.2
Hoobs 3: 3.2.10
Node: 12.16.2 

Best regards,
Christian

**Comment by normen** [comment]
Hi. For support with HOOBS installs please contact the HOOBS team directly.

Am 21.11.2020 12:02 schrieb Christian Kramer:

**Comment by chrstnkrmr** [comment]
Hoobs said: Contact the plugin developer!

**Comment by normen** [comment]
Well I didn't advertise any support here.

Am 21.11.2020 12:23 schrieb Christian Kramer:

**Comment by chrstnkrmr** [comment]
I don’t need support.
I only want report an issue.

Maybe you can check and debug it.

**Comment by normen** [comment]
I can't debug "the tile disappeared", there might be a myriad of reasons why that is happening.

See, github is where users help developers, not the other way around. Look a bit more at the behavior, add the `"debug":true` switch to your TV's config entry and play around, then give me all relevant information and log output so I get an idea what might be happening. Everything else (i.e. me asking you everything) _is_ pretty much support.

Am 21.11.2020 12:26 schrieb Christian Kramer:
