### ISSUE TITLE
Channels missing

### ISSUE THREAD

**Issue by shannondpasto** [normen/homebridge-bravia#146]
Hi. 

There are whole bunch of channels missing from the list. Basically any channel with an LCN of 9 as listed on https://en.wikipedia.org/wiki/List_of_digital_television_channels_in_Australia (in Melbourne). Any ideas?

Thanks,
Shannon

**Comment by normen** [comment]
The plugin will only display the channels that the TV reports in one go when queried for channels. For most TVs thats the first 50 channels as programmed in the TV.

Am 29.11.2020 00:57 schrieb shannonpasto:

**Comment by shannondpasto** [comment]
Ok. The homebridge-bravia-tvos homebridge plugin returns 61 channels which includes the missing 9 LCN ones.

**Comment by normen** [comment]
Okay. So you can use that if you need 61 channels.
