### ISSUE TITLE
Inputs not loading

### ISSUE THREAD

**Issue by Chibale11** [normen/homebridge-bravia#147]
I am getting this error: 

[BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}

This is my config:

        {
            "tvs": [
                {
                    "name": "Family Room TV",
                    "ip": "192.168.1.27",
                    "externalaccessory": false,
                    "debug": true,
                    "soundoutput": "speaker",
                    "sources": [
                        "hdmi"
                    ]
                }
            ],
            "platform": "BraviaPlatform"
        },

**Comment by Chibale11** [comment]
> I am getting this error:
> 
> [BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}
> 
> This is my config:
> 
> ```
>     {
>         "tvs": [
>             {
>                 "name": "Family Room TV",
>                 "ip": "192.168.1.27",
>                 "externalaccessory": false,
>                 "debug": true,
>                 "soundoutput": "speaker",
>                 "sources": [
>                     "hdmi"
>                 ]
>             }
>         ],
>         "platform": "BraviaPlatform"
>     },
> ```

Resolved, had to manually add "extInput:hdmi" to config file. The Plugin setup form does not properly add it.

**Comment by normen** [comment]
>  The Plugin setup form does not properly add it.

Can't reproduce, what did you enter?

**Comment by RossiHovitez** [comment]
I got the same thing

this is my config. Do I need to add something?
![B7FBDF53-08D2-4082-9206-91CE51375AD6](https://user-images.githubusercontent.com/81195491/112185251-f5aef900-8bf7-11eb-9405-a82498faffa8.jpeg)

**Comment by normen** [comment]
Same question: what did you enter in the config UI? The readme describes the options.

**Comment by RossiHovitez** [comment]
Hi
The IP
Name of TV
Then tv popped up with 4 digits
Entered them then it worked

but when I updated a config for another plugin the service stopped 
When it restarted tv disappeared 

so did reboot and 4 digits appeared. I’ve not done another plugin refresh but want to. Suspect tv will disappear again

**Comment by normen** [comment]
You seem to be talking about something else now. Anyway I can't really say what you mean by "plugin refresh", but the behavior sounds like you're deleting your plugin cache along with the login info for the TV for some reason.
