### ISSUE TITLE
Can not tun TV on

### ISSUE THREAD

**Issue by suddy** [normen/homebridge-bravia#148]
I am with the last version of homebrige and this plugin, with the pin of setting, I can control the tv and tun off, but when I use home app to tun on the TV, It can not wok. Can you help to tell me How can I do some troubleshotting for this problem, or how can i fix it?

**Comment by suddy** [comment]
I find something update:
when let the mac addr is null, all is work fine.
and when input the mac addr of tv, it can not tun on after tun off.
I think maybe wol is not work for me, but I don't know why, please help if any idea I can try for this problem?

**Comment by normen** [comment]
As the manual and the settings panel say - you only set a MAC address if you want to use WOL.
