### ISSUE TITLE
TV was an accessory, stopped responding, deleted now cannot add back

### ISSUE THREAD

**Issue by spikenheimer** [normen/homebridge-bravia#151]
I have 2 Bravia TVs that were working fine up until a few weeks ago when one of them stopped "responding" in home.app. aka it was showing "no response".  

i tried restarting homebridge, made sure it was all up to date etc etc.  (HB 1.3.4, bravia-2.4.8, node 15.12.0, npm 7.7.5)

so i tried deleting the accessory from Home.app and re-adding it.

the attempt to re-add the accessory failed. ( hit + accessory, manually used the code from the homebridge log, and the gear icon just keeps spinning) 
then tried to delete homebridge as a remote device from the tv itself, restarted homebridge, re-authenticated the tv w/ the 4digit code and tried to re-add the accessory and its still spinning.

the config snippet:
``` {
            "tvs": [
                {
                    "name": "Bravia 65",
                    "ip": "192.168.24.32",
                    "externalaccessory": true,
                    "soundoutput": "speaker",
                    "sources": [
                        "extInput:hdmi",
                        "extInput:cec"
                    ]
                },
                {
                    "name": "Bravia 75",
                    "ip": "192.168.24.33",
                    "externalaccessory": true,
                    "soundoutput": "speaker"
                }
            ],
            "platform": "BraviaPlatform"
        },
```

**Comment by normen** [comment]
Try giving them a different name, HomeKit is funny that way with external accessories.
