### ISSUE TITLE
No sound when turning ON Bravia TV

### ISSUE THREAD

**Issue by Jer-emy** [normen/homebridge-bravia#152]
Hello,

When I'm turning ON my TV, I do not have sound and I have to turn OFF and turn ON again to get sound.
I'm using a soundbar handled in a HDMI port and it switch ON directly when I'm turning ON my TV.

In the configuration of the plug-in, I have set "sound output" as "SonyAudio" because I have alsa a plug-in for my soundbar.
Does it the root cause of my issue?

>         {
>             "name": "Sony Audio Platform",
>             "platform": "SonyAudio"
>         {
>             "tvs": [
>                 {
>                     "name": "TV salon",
>                     "ip": "xxx.xxx.x.xx",
>                     "woladress": "xxx.xxx.xxx.x",
>                     "mac": "xx:xx:xx:xx:xx:xx",
>                     "externalaccessory": true,
>                     "soundoutput": "SonyAudio",
>                     "updaterate": 3000
>                 }
>             ],
>             "platform": "BraviaPlatform"
>         }

**Comment by normen** [comment]
No idea, did you try simply setting the normal "speaker"?
