### ISSUE TITLE
This plugin slows down homebridge warning

### ISSUE THREAD

**Issue by wavded** [normen/homebridge-bravia#154]
https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings#this-plugin-slows-down-homebridge

Started getting this today.  Documentation recommends I report. So that's what I did. Thanks for plugin BTW!

<img width="952" alt="Screen Shot 2021-05-12 at 10 47 09 AM" src="https://user-images.githubusercontent.com/26638/118004820-6bd5ff00-b30f-11eb-9c5f-e1931e0be32f.png">

**Comment by normen** [comment]
Yeah, these new warnings are pretty annoying. If you can live with not being able to turn off your lights in the half-second that your TV sometimes needs to react to a request you (and homebridge) should be fine 😁 Maybe your network / wifi connection is slow today or something?

**Comment by wavded** [comment]
> Maybe your network / wifi connection is slow today or something?

Possibly.  I'll keep a look out.  Thx for responding!
