### ISSUE TITLE
Error in log?

### ISSUE THREAD

**Issue by LeonKaterbarg** [normen/homebridge-bravia#156]
Hello, I tried to connect my Sony Bravia display to Hoobs.
but I get the following error in my log, what am I doing wrong...?

Thanks in advance!
Greetings from The Netherlands.

28-7-2021 14:23:47Bravia Bridge starting
28-7-2021 14:23:50Bravia BridgeLoaded plugin 'homebridge-bravia'
28-7-2021 14:23:50Bravia BridgeLoading 1 platforms...
28-7-2021 14:23:50Bravia BridgeBraviaPlatformCreating new accessory for TV Sony
28-7-2021 14:23:50Bravia BridgeBraviaPlatformNew TV TV Sony, will be queried for channels/apps and added to HomeKit
28-7-2021 14:23:50Bravia BridgeBridge is running on port 55826.
28-7-2021 14:23:50Bravia BridgeBraviaPlatformError:  Error: connect ECONNREFUSED 192.168.1.88:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.88',
  port: 80

**Comment by normen** [comment]
Looks like your TV can't be connected to in your network. I don't do support for running this plugin in HOOBS though, ask their support.
