### ISSUE TITLE
I can not insert more than one application.

### ISSUE THREAD

**Issue by Pieromodi** [normen/homebridge-bravia#157]
I have successfully added the Netflix app and it shows up as an input in the Home app. Now I want to add a weather app, but it doesn't work. Does anyone know the reason. 

  "applications": [
                        {
                            "title": "Netflix"
                        },
                        {
                            }, { "title": "WeatherLive"
                        }
                    ]

**Comment by normen** [comment]
Just try part of the name, e.g. "Weather". Whats shown on the screen of your TV isn't necessarily the "real" name of the application.
