### ISSUE TITLE
How can I get the TV to show as TV icon 

### ISSUE THREAD

**Issue by SeanHama** [normen/homebridge-bravia#158]
![sony tv](https://user-images.githubusercontent.com/57736130/131957311-50e1ef54-76f2-499e-a5d6-9f3b60b36b7d.jpeg)
Thanks for a simple solid plugin. How do I get the TV to show as a TV device not a Home Icon?

Also, the TV doesn't appear on the top  of homekit with other on devices/accessories when its on.

**Comment by normen** [comment]
You have to use external accessory mode for that.
