### ISSUE TITLE
TV will not shown as TV icon

### ISSUE THREAD

**Issue by sadden3194** [normen/homebridge-bravia#159]
Hello,

thank you for this plugin !
But:

The first time I added my tv it will shown in HomeKit as a house icon and I can't change this.
I road that I have to set the external accessory mode.

```
{
            "tvs": [
                {
                    "name": "MY TV",
                    "ip": "TV_IP",
                    "mac": "TV_MAC",
                    "externalaccessory": true
                }
            ],
            "platform": "BraviaPlatform"
        }
```

But after that the device will not shown anymore in homekit. where is my fault?

**Comment by normen** [comment]
Check the README. It explains how to add an external accessory.
