### ISSUE TITLE
Found unparsable model name (MediaRenderer) for device KD-75X9400E, usn: "uuid:23456789-1234-1010-8000-045D4BD60953". Skipping it.

### ISSUE THREAD

**Issue by SeanHama** [normen/homebridge-bravia#161]
Hi - I keep getting this error, any ideas on how to fix it up please?
thanks in advance

<img width="1221" alt="Screen Shot 2021-09-15 at 12 47 47 pm" src="https://user-images.githubusercontent.com/57736130/133362232-fe621a53-3754-4ae9-b4ae-64b354b190f0.png">

**Comment by normen** [comment]
Thats not an error message of this plugin.
