### ISSUE TITLE
Missing model name and serial number

### ISSUE THREAD

**Issue by git2james** [normen/homebridge-bravia#165]
The Home app and plugin details show default-model and default-serialnumber. It looks from previously closed issues that this should be read from the TV, but it is not in my case. Any ideas?

![IMG_F897DE7AD4E8-1](https://user-images.githubusercontent.com/4472496/147925492-7104a72b-17b0-49b2-940a-cc6aa3d904b3.jpeg)

**Comment by normen** [comment]
No, this info isn't read and not displayed. What you see is what is intended.

**Comment by SalikovAlex** [comment]
@normen may be we can change Something? 
Because some apps, that use HomeKit can't work correctly if SerialNumer is so strange.
