### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0') - No response from HomeKit, if the TV is on.

### ISSUE THREAD

**Issue by azagramac** [normen/homebridge-bravia#166]
If the TV is off, you can turn it on from Homekit, but if it is on, you can't turn it off, also the channel list and inputs are no longer displayed in Homekit... 
It has been linked again from 0, with the same result. 

**Homebridge version:** 1.3.9
**Node.js version:** v16.13.1
**Npm version:** v8.1.2
**Plugin version:** homebridge-bravia v2.4.9 
**iOS version:** 15.2

`[1/5/2022, 9:57:13 AM] [BraviaPlatform] TypeError: Cannot read properties of undefined (reading '0')
    at onSucces (/homebridge/node_modules/homebridge-bravia/index.js:501:36)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-bravia/index.js:960:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by normen** [comment]
What TV is it? I guess its not compatible.

**Comment by azagramac** [comment]
Until a few days ago if it has been compatible? 

The problems started with the previous Homebridge update, v1.3.8, up to that moment everything was fine, since that version... problems. 

The TV is a Sony Bravia KDL-40W705C

I've been using the plugin for 1 year, and I've never encountered this problem...

**Comment by normen** [comment]
Well all I can say is that your TV - instead of reporting a list of applications - reports a big fat `0` now. Homebridge v1.3.9 works fine for me. Maybe your TV had an update?

**Comment by azagramac** [comment]
The TV has not received updates for more than 1 year, Sony stopped supporting it some time ago... the funny thing is that until 1.3.8 everything works perfectly, in 1.3.8 most of the time it gave problems, and even stopped showing the icon of a TV in HomeKit and showed a house, now in 1.3.9, nothing at all.

**Comment by normen** [comment]
So do you use external accessory mode or...?
