### ISSUE TITLE
Help with Gen1 smart Bravia - doesn't use pin

### ISSUE THREAD

**Issue by E46er** [normen/homebridge-bravia#169]
Hi all,
Is there any way to use this plugin with Gen1 smart bravias?
They do not require pin or PSK etc

I have 2 units that would be great to get working with homebridge!

Thanks for your help

**Comment by normen** [comment]
It works with a lot of Sony TVs but I don't know what exactly you mean so I guess just trying it would make most sense.

**Comment by E46er** [comment]
On the first generation smart bravias ( non android ), there was no pin or psk security. 
I cannot get the plug-in to work without entering a pin for the tv, but of course the tv does not need one.

**Comment by normen** [comment]
You can try and set `pwd = "mybasicpass"` in your `config.json` after setting a basic auth password in your TV.

**Comment by E46er** [comment]
The TV has no option to set any type of password / pin or PSK.
Is there a config option that removes the Pin / authentication requirement?

**Comment by normen** [comment]
What happens when you set a password as I described?

**Comment by E46er** [comment]
[BraviaPlatform] Error:  Error: connect EHOSTDOWN 192.168.8.102:80 - Local (192.168.8.91:51530)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:454:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -64,
  code: 'EHOSTDOWN',
  syscall: 'connect',
  address: '192.168.8.102',
  port: 80

**Comment by E46er** [comment]
sorry ignore that log - the IP changed.
Now I have:
[BraviaPlatform] Need to authenticate with TV!
[2/7/2022, 9:14:08 AM] [BraviaPlatform] Please enter the PIN that appears on your TV at http://Deans-Mac-mini.local:8999
[2/7/2022, 9:14:08 AM] [BraviaPlatform] PIN entry web server listening

**Comment by normen** [comment]
That message means that the TV can't be connected to at all, it doesn't even get to the authentication stage. Might be because its not compatible to the http protocol of the current TVs or that theres a network issue.

**Comment by normen** [comment]
> [BraviaPlatform] Need to authenticate with TV!
> [2/7/2022, 9:14:08 AM] [BraviaPlatform] Please enter the PIN that appears on your TV at http://Deans-Mac-mini.local:8999

If this appears even though you have a "pwd": "blah" entry in your config.json then I guess you're out of luck, the TV just won't talk to us. Its kind of strange that there would be a http interface on that TV without any security option though.

**Comment by E46er** [comment]
my research has found that the gen 1 bravias, built around 2013 did not have any form of security option. They operate with the same IP protocol thou..
I'm attempting to modify the index.js to remove the authentication part.. but I'm a learner with json etc, so I'm guessing a fair bit!

**Comment by normen** [comment]
> my research has found that the gen 1 bravias, built around 2013 did not have any form of security option. They operate with the same IP protocol thou..
> I'm attempting to modify the index.js to remove the authentication part.. but I'm a learner with json etc, so I'm guessing a fair bit!

If you set a "pwd" then the request is basically a normal request with a password in the header. The TV is still answering with nothing apparently.

If you want to brute-force avoid the check make the if check in line 257 always fail.
