### ISSUE TITLE
TV Registration

### ISSUE THREAD

**Issue by JGP7229** [normen/homebridge-bravia#172]
Just recently my main TV which is already HomeKit compatible randomly prompts me to register it with the registration code. The TV's ip is not one of the registered TVs within the plugin. Is there a way to prevent this?

Thank you

**Comment by normen** [comment]
I have a piece of string in my hand, can you tell me how long it is? I couldn't think of a way how the plugin would prompt the TV without it having the IP. Maybe your router reassigns the IP?
