### ISSUE TITLE
Turns TV Off, but not On. Also no volume

### ISSUE THREAD

**Issue by JossConnolly** [normen/homebridge-bravia#173]
The plugin was super easy to install, and does a great job a turning the TV off. But it can't turn the tv on through the Home App.

Also, there's no options for adjusting volume.

I've not touched any JSON config code.

Any ideas?

**Comment by normen** [comment]
Check the README, you'll have to enable remote start or use WOL. You can change the volume with the volume buttons of your phone when using the Apple Remote (swipe down on the top right of your phone).
