### ISSUE TITLE
ios 15 does not work volume control

### ISSUE THREAD

**Issue by solomatinma** [normen/homebridge-bravia#174]
Hello, lovely plugin! but there is a problem the volume control does not work, please help!I open the remote control, select the TV, the volume buttons do not work.

**Comment by normen** [comment]
What does work?

**Comment by solomatinma** [comment]
Only the iphone 12 pro max does not work! iPad pro 11,iphone 8,iphone x works.

**Comment by normen** [comment]
I am testing with a 13 Pro, no idea why it wouldn't work.
