### ISSUE TITLE
Keeps sending this error

### ISSUE THREAD

**Issue by dpyy** [normen/homebridge-bravia#18]
Everything seems to be working except if I run homebridge in the command line I can see the output keeps sending this every few seconds

[BraviaPlatform] Error?  {"error":[3,"Illegal Argument"],"id":13}

**Comment by normen** [comment]
Thats probably the check for the TV being on. I guess the switch in HomeKit doesn't turn on/off if you turn the TV on/off either.

**Comment by dpyy** [comment]
What does that even mean? Why are you closing this? It's still outputting an error, it works but gives printing the error

**Comment by normen** [comment]
Yeah, nothing that warrants an issue in the bug tracker. Your TV doesn't support checking if its turned on.
