### ISSUE TITLE
Feature Request: Add Support for HTTP commands to control volume/mute

### ISSUE THREAD

**Issue by jordanhanna1** [normen/homebridge-bravia#180]
Hi there!
I would like to control a separate audio device with HTTP commands for volume up/down/mute, whilst leaving the primary TV controls to the Bravia.  Similar concept to homebridge-http-tv.
In addition, it would be great to have additional on/off HTTP commands run when triggering the power on/off.
Love to hear your thoughts, thanks!

**Comment by normen** [comment]
Should be easy to add, you just need to add the http calls in the respective functions, e.g. here https://github.com/normen/homebridge-bravia/blob/adee528c55f89db92e842e3301e9df58ade5ee19/index.js#L896

In general I'd rather do that with a HomeKit automation (if TV turns on, turn on that HTTP device - theres HTTP plugins for homebridge)
