### ISSUE TITLE
Port number is hard coded

### ISSUE THREAD

**Issue by pkhavkine** [normen/homebridge-bravia#22]
Hi.

It looks like my TV is using port 9080 instead of 80. The port is hard coded, can this be configurable?

Thanks
Paul

**Comment by normen** [comment]
Interesting.

Yeah, that should be easily possible, if you want you can send me a PR as I don't know when I'll get around to working on this - my TV runs on 80 ;)

**Comment by normen** [comment]
The latest version allows setting the port number via the "port" option, make sure its a string parameter, i.e. "port": "80".
