### ISSUE TITLE
Plugin constantly throws error event

### ISSUE THREAD

**Issue by twcau** [normen/homebridge-bravia#24]
Following error event is constantly being thrown, after 1st time execution where the PIN was successfully entered and TV confirmed registration:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/sonycookie'
```

This would seem to indicate that the plugin is looking in the wrong directory path for the sonycookie that is generated after pairing.

TV model is a KD-55X8500E, running v7.0, with kernel 3.10.79, security patch level 1 AUG 2017.

**Comment by normen** [comment]
Please only use this bug tracker for actual bugs with proper descriptions and information. I can not give support for this free software, if you fail to set it up you'll have to live with that.

(Re-)Read the manual and double-check if the given paths actually exist on your system or if you should supply your own values.

**Comment by twcau** [comment]
This would have been a good response:

> Seems like you just missed the value `cookiepath` in your config.json, hence the error.

This would have been an even better response, if added on:

> This identifies out a good point, and when I have some time - i’ll look at updating this package to make it easier, by having it look at the homebridge install path, and if a value for `cookiepath` isn’t set in config.json (given my documentation doesn’t indicate the need for this value as a default), then it’ll create the file and place it in a better default location (rather than the path that is currently hardcoded as the default).

Not everyone gets it right the first time, and even those of us who spend good portions of the day writing documentation for the last 10+yrs miss details from time to time.

Either of the responses i’ve suggested above would have been far easier to write, and have come across far nicer, than what you replied with - which at best came across quite rude, and didn’t exactly paint you in the best light.

**Comment by normen** [comment]
If you re-read your comment it implies knowledge on my side that only you had. Anyway you solved your problem (apparently with my nudge) and in addition can feel elevated for trying to better somebody elses ways - so a win-win for you.

Edit: Oh and heres a good response for you:
> I have found the issue and prepared a PR that updates the documentation to help people find such issues better. I even added code that should find the correct path automatically, maybe you can test it on your system. Cheers!
