### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/sonycookiepin'

### ISSUE THREAD

**Issue by WillBishop** [normen/homebridge-bravia#25]
I get this upon the first setup:

```
prompt: pin:  2711
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/sonycookiepin'

```

In the TV settings, `homebridge` is listed as a remote. But I cannot use it.

**Comment by normen** [comment]
Please read the manual on how to set the cookie path, note its a FILE name not a folder name, so don't make a folder with that name. Otherwise please understand that this is not a support forum but a bug tracker and I can not give support for this free software.
