### ISSUE TITLE
TV is just a switch and nothing else works

### ISSUE THREAD

**Issue by hakt0-r** [normen/homebridge-bravia#27]
I am newbie to this but I went through all the config and setup as directed and I can see the TV just as a switch. I cannot control the speaker nor any apps.

Please Help.

**Comment by normen** [comment]
Sadly this is not a support forum but a bug tracker, I can't give support for this free software. Re-read the manual, its normal that the other options don't appear in Apples Home app.

**Comment by hakt0-r** [comment]
Hi normen, thanks for the reply. I am reporting a bug I've got a Sony Bravia KDL-55HX850 and I've tried setting it up as instructed here but sadly no go. Here is my config
    "platforms": [
        {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                   "name": "TV",
                   "ip": "192.168.1.3",
                   "tvsource": "tv:dvbs",
                   "soundoutput": "speaker",
                   "listapplications": 0
                }
            ]
        }
]
I can turn it on/off only. Thanks in advance :-) 

If you want any more debug info I am happy to provide.

**Comment by normen** [comment]
Did you even read the answer?

**Comment by hakt0-r** [comment]
my mistake. Sorry!

**Comment by hakt0-r** [comment]
Sorry to hijack this thread, but are you interested in making one more homebridge plugin? if it helps I can fund it. reach out to me hakt0r@icloud.com if not sorry to bother you again.
