### ISSUE TITLE
Can you add multiple TVs?

### ISSUE THREAD

**Issue by soomrox** [normen/homebridge-bravia#29]
I have added Two Sony TVs in my config.json> It shows it is loading fine in homebridge and shows. It does not let me control it though and did not ask for the pin of the second TV. Any ideas?

**Comment by normen** [comment]
Hm, not really, I added support for multiple TVs when I moved the plugin to "platform" instead of "accessory" but to be honest I never really tried it as I have only one Sony Android TV..

Thinking about it I guess the files where it stores the TV code would get mixed up...

Any log output otherwise?

**Comment by normen** [comment]
Uhm, sorry, I guess I wasn't explicit enough with the possible workaround - try to add a specific "cookiepath" to each entry, see the README.

**Comment by soomrox** [comment]
Thanks for the prompt reply.

How would I add the cookiepath into my config (confused with what to add to the line"[user home]/.homebridge/sonycookie")

Below is my config if you can help

"platforms": [{

			"platform": "BraviaPlatform",
			"tvs": [{
					"name": "Bedroom TV",
					"ip": "192.168.1.230",
					"tvsource": "tv:HDMI 3",
					"soundoutput": "speaker",
					"listapplications": 0
				},
				{
					"name": "SNUG ROOM TV",
					"ip": "192.168.1.221",
					"tvsource": "tv:HDMI 2",
					"soundoutput": "speaker",
					"listapplications": 1
				}
			]
		},

**Comment by normen** [comment]
"listapplications": 1,
"cookiepath": "/path/to/the/FILE"

remember it's a FILE name, don't make a folder with that name, only make the parent folder. You can use the same folder for each TV but not the same file name.

**Comment by normen** [comment]
So? Remember, this is github, where users help developers, not the other way around.

**Comment by soomrox** [comment]
Sorry, I have not had a chance to do anything. Got home late last night and same again tonight.  I get many hours on the weekend to play around with this. Promise I will update you as soon as I can. I am as keen and eager :)

**Comment by normen** [comment]
Cool, just wanted to make sure to get some tests in an actual multi-TV setup before you start dabbling with other stuff - I know how this works ;)

**Comment by soomrox** [comment]
Hi just got few minutes to remotely logon to my box and wrote this up for the config

"platforms": [{

			"platform": "BraviaPlatform",
			"tvs": [{
					"name": "Bedroom TV",
					"ip": "192.168.1.230",
					"tvsource": "tv:HDMI 3",
					"soundoutput": "speaker",
					"listapplications": 0,
					"cookiepath": "/root/.homebridge/sonycookie"
				},
				{
					"name": "SNUG ROOM TV",
					"ip": "192.168.1.221",
					"tvsource": "tv:HDMI 2",
					"soundoutput": "speaker",
					"listapplications": 1
				}
			]
		},



So as you can see in the picture it has created a pin file and the sonycookie. I am assuming now that when I start the second tv it will try and create a new pin.

![sonycookie](https://user-images.githubusercontent.com/37217099/37715206-588328b8-2d13-11e8-8afc-9253a169e799.JPG)

**Comment by normen** [comment]
Yeah but the point was to give a different file name for each TV so they don't mix up. The way it is now both will use "/root/.homebridge/sonycookie" because by default it uses "[user home]/.homebridge/sonycookie" which IS "/root/.homebridge/sonycookie" if you run homebridge as root.

So add an entry to the second tv as well, something like
"cookiepath": "/root/.homebridge/second_sonycookie"

**Comment by soomrox** [comment]
Normen, great news. Both TV appear on Home now :)

![tv](https://user-images.githubusercontent.com/37217099/37734773-0f1c3814-2d44-11e8-93af-cedd5fe0b690.PNG)

For some reason I had to reinstall the homebridge server (nothing to do with the TVs) so when I got it back up it picked the original TV but did not create a pin file as it didn't ask for one, the 2nd TV it has done everything correctly. 

Now I did not mention this before as I wanted to test on both TVs. So maybe you can help with this. Through Home and Voice Siri I can turn the TVs off but cannot turn them on or do anything else. Any ideas :)

**Comment by normen** [comment]
The TV usually stores the key that the plugin reports as "authorized" so you don't need to register (i.e. enter the PIN) again.

**Comment by normen** [comment]
So it seems like everything is working, I'll look into automatically generating different names for the different TVs in one of the next versions, if you already enter the path directly (as you now did) nothing will change. Thanks for testing!
