### ISSUE TITLE
First Pin input

### ISSUE THREAD

**Issue by det-box** [normen/homebridge-bravia#3]
Hello,
in the PIN input I get an error:
events. js: 163
      throw it; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/var/homebridge/plugin-persist/sonycookie/'

The entry "cookipath" :
 'cookiepath': '/var/homebridge/plugin-persist/sonycookie'

please Help

Thanks

**Comment by normen** [comment]
You have to enter the path to a FILE, not a directory, so make that
"/var/homebridge/plugin-persist/sonycookie/cookiefile" instead

**Comment by det-box** [comment]
Oh, OK
Will test it right now tonight

**Comment by det-box** [comment]
File, that was it.
Is done with it.

Thank you

**Comment by normen** [comment]
Glad it worked for you. Did you have to enter the PIN only once? Did the process work properly otherwise?

**Comment by det-box** [comment]
PIN input worked,
control with the EVE APP works fine.
I mostly TV on / off and sound on / off.

It would be good if you could select the input with Next input.

Many thanks

**Comment by normen** [comment]
You mean things like HDMI input etc? I myself do that via the connected devices. For example I control my Playstation via HomeBridge and when it turns on the TV automatically turns on as well. But I'll look into that, thanks for the feedback and input!

**Comment by det-box** [comment]
might help these codes on
https://github.com/arnif/sony-bravia-remote/blob/master/src/ActionMap.js

**Comment by normen** [comment]
Nah, I'm using the HTTP API directly instead of using infrared commands via HTTP. Anyway, thanks for the help, closing this issue now. Have fun with your HomeKit setup :)

**Comment by icanic** [comment]
Greetings!
How to change the path?
I have the same error.
