### ISSUE TITLE
Channels not working

### ISSUE THREAD

**Issue by vvtvv** [normen/homebridge-bravia#32]
For some reason channels have no effect. Otherwise works as described.

Thanks for sharing a great plugin!

**Comment by normen** [comment]
As the channels have to be set via an URL and not simply via a channel number the TV is polled for a list of all channels and their URLs, depending on the TV and setup that might take a while as they are polled in chunks of 50 channels each - large XML outputs are sometimes garbled on the Android TV system.

Depending on your setup that might or might not be the issue, the information you gave doesn't allow for a more in depth analysis. It might also be your TV just doesn't support this way of setting channels.
