### ISSUE TITLE
HomeKit Support

### ISSUE THREAD

**Issue by donavanbecker** [normen/homebridge-bravia#33]
Now that HomeBridge has been updated to support tv services, can this be added to this Plugin?

**Comment by normen** [comment]
I doubt it as that requires an AirPlay2 compatible device

**Comment by donavanbecker** [comment]
Would you be able to do this?

https://twitter.com/KhaosT/status/1088680375398744064

https://twitter.com/KhaosT/status/1088678984970162176

**Comment by d0n4v4nb3ck3r** [comment]
https://twitter.com/KhaosT/status/1088678984970162176
