### ISSUE TITLE
iOS 12.2 TV profile support

### ISSUE THREAD

**Issue by donavanbecker** [normen/homebridge-bravia#34]
Would you be able to do this?

https://twitter.com/KhaosT/status/1088680375398744064

https://twitter.com/KhaosT/status/1088678984970162176

- [ ]

**Comment by normen** [comment]
Interesting, I'll look into it.

**Comment by normen** [comment]
Yeah, it will make the plugin much slimmer and easier to handle - I'll add it when 12.2 is released, I don't want to play around with betas atm.

**Comment by KennyVB** [comment]
just released ios 12.2!!

**Comment by normen** [comment]
Hehe, yeah, I have a basic version running that allows switching the TV on and off and using the remote app with the TV, including volume. Adding the input selection will still take a while though as the whole initialization order has to change for that.

**Comment by normen** [comment]
Added in v 1.0
