### ISSUE TITLE
Strange Issue - channels in low numbers >6 go to radio instead of TV

### ISSUE THREAD

**Issue by KennyVB** [normen/homebridge-bravia#35]
Hello

recently installed this wonderfull plugin!
worked perfectly, but then all of a sudden
all channel below 6 on dvbt go to radio instead of TV
i used to have a channel 2 scene in the app. Elgato EVE, now afer a reboot
it keeps changeing to radio channel 2 ?!?!

i tried removing the radio channels all together from the TV
but they just bump to 3006 etc. and then the channel 2 goes there instead.. weird 

i have a Sony Android TV 55xf8096 and recetly updatet it Android 8.0. worked as i said perfect, until 1 reboot of the homebridge :) all other things work, got a channel scene for channel 56 BAM works but below 6 are suddenly all radio
Ask i shall give everything. can't seem to find a log "without its the homebridge spamming log" with any usefull, but if you want. dont hesitate to ask :) would very mush appriciate to get around this :) 

`{
			"platform": "BraviaPlatform",
			"tvs": [{
				"name": "TV",
				"ip": "10.0.2.12",
				"tvsource": "tv:dvbt",
				"soundoutput": "speaker",
				"maxchannels": 100,
				"listapplications": 0,
				"apps":[
					"com.sony.dtv.com.netflix.ninja.com.netflix.ninja.MainActivity",
					"com.sony.dtv.com.plexapp.android.com.plexapp.plex.activities.SplashActivity",
					"com.sony.dtv.dk.tv2.tv2playtv.dk.tv2.tv2playtv.splash.SplashActivity"
				]
			}]
		}`

**Comment by normen** [comment]
Hm, dunno really.. The  way channels work is relatively complex as the plugin has to call each channel by an URL so each time it boots it asks the TV about the URLs for each channel and uses those to start the channels. So maybe reboot the TV and then reboot homebridge to make sure everything is the same.

**Comment by normen** [comment]
Also make sure you don't have a maxchannels value above your actual channel count.

**Comment by normen** [comment]
I guess this issue is now obsolete with iOS 12.2 support :)
