### ISSUE TITLE
Not all inputs listed

### ISSUE THREAD

**Issue by normen** [normen/homebridge-bravia#36]
There seems to be an asynchronous execution issue in the startup sequence. Sometimes the TV initializes before the TV reported back the list of all channels.

P.S.
In general, when using a tvsource not all channels may be listed. This is due to the TV only sending a certain amount of channels per request (about 50). This has nothing to do with the above. Previous attempts to receive all channels through consecutive requests failed so a new way might be implemented.

**Comment by huongminh** [comment]
can a selective list of channels, apps be configured in the config.json?

**Comment by normen** [comment]
>can a selective list of channels, apps be configured in the config.json? 

@huongminh No, you can configure your TV to have the „needed“ channels first though.

**Comment by huongminh** [comment]
Thank you! It would be great to show only favarite apps and channels on the Home App while a full lust of some tens/hundreds apps/channels are still there on the tv when you need them. 


Sent from Yahoo Mail for iPhone


On Wednesday, April 24, 2019, 12:10 AM, Normen Hansen <notifications@github.com> wrote:



can a selective list of channels, apps be configured in the config.json?


@huongminh No, you can configure your TV to have the „needed“ channels first though.

**Comment by normen** [comment]
>Thank you! It would be great to show only favarite apps and channels on the Home App while a full lust of some tens/hundreds apps/channels are still there on the tv when you need them.  ...

@huongminh Yeah, I was thinking about using the favorites in the TV for that, in theory you could select them in the HomeKit TV settings, set them in the TV through the HTTP API etc. but in the end it‘s too much work - a PR is welcome though ;)

**Comment by pmoon00** [comment]
This plugin has been great for me and I've just updated recently to have the new TV functionality in HomeKit.  I've found that in the HomeBridge logs it shows all my channels, but they aren't available in the Home app itself.  Am I missing something?  Any help would be appreciated.

<img width="480" alt="Screen Shot 2019-06-13 at 6 14 34 PM" src="https://user-images.githubusercontent.com/14009133/59408057-2f3db800-8e07-11e9-93d1-a02807c587bc.png">
<img width="480" alt="Screen Shot 2019-06-13 at 6 14 51 PM" src="https://user-images.githubusercontent.com/14009133/59408059-2f3db800-8e07-11e9-9b45-d1de4a54c64f.png">

**Comment by mmax-nl** [comment]
> This plugin has been great for me and I've just updated recently to have the new TV functionality in HomeKit. I've found that in the HomeBridge logs it shows all my channels, but they aren't available in the Home app itself. Am I missing something? Any help would be appreciated.
> 
> <img alt="Screen Shot 2019-06-13 at 6 14 34 PM" width="480" src="https://user-images.githubusercontent.com/14009133/59408057-2f3db800-8e07-11e9-93d1-a02807c587bc.png">
> 
> <img alt="Screen Shot 2019-06-13 at 6 14 51 PM" width="480" src="https://user-images.githubusercontent.com/14009133/59408059-2f3db800-8e07-11e9-9b45-d1de4a54c64f.png">

I have the same issue. From the log I see a lot of channels being listed but in the input they are not there!

**Comment by mmax-nl** [comment]
Also for my KD-65XE9005, a list of channel is present in the log, however in the HomeKit tile, only the HDMI inputs are visible.

**Comment by pmoon00** [comment]
> Also for my KD-65XE9005, a list of channel is present in the log, however in the HomeKit tile, only the HDMI inputs are visible.

Try update your HomeKit Hub (mine was an Apple TV), and then restarting your Homebridge.  Seems to have fixed it for me.

**Comment by dg1yds** [comment]
Same issue here with 65XD9305 - list of channel is present in the log, only the HDMI inputs are visible. Update of HomeKit hub (Apple TV) and restart does not fix the issue.

**Comment by nrushforth** [comment]
I have the same issue with KD55AG8 TV. Only a subset of channels are received and nothing then listed in HomeKit for the channels.

**Comment by mmax-nl** [comment]
After updating my Hoobs I see the partial list in the tile.
![6368931A-8AE7-491A-9B11-0FB93845DC3B](https://user-images.githubusercontent.com/58346648/73553795-d2047e80-444a-11ea-976f-ba5333368ea1.png)

**Comment by normen** [comment]
Most of the posts here are not not relevant to this issue, HomeKit (or HomeBridge/HAP-Nodejs) seems to have some bug where the channel info isn't propagated properly along all HomeKit devices. You can see it in action when changing the channel count and restarting HomeBridge for examle. These issues usually resolve themselves after a while as I'm sure some of the posters here could confirm.

What this issue is actually about is a limit on the channel count, about 50 channels or so. If you hit that then thats what this issue describes. If you don't see channels or only a handful then the issue is with HomeKit/Bridge.

**Comment by normen** [comment]
Lol, just in that moment where I posted somebody actually cared to update their help-seeking post accordingly :)

**Comment by mmax-nl** [comment]
![Screenshot 2020-01-31 at 6 50 32 PM](https://user-images.githubusercontent.com/58346648/73562098-b1442500-445a-11ea-8e8d-25acd0c1e763.png)
On top of still only seeing a partial list of the channels available, now the TV is seen as two different devices!

**Comment by mmax-nl** [comment]
I can confirm that I only receive the first 48 channels:
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input HDMI 1
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input HDMI 2
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input HDMI 3/ARC
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input HDMI 4
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input NPO 1 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input NPO 2 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input NPO 3 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input RTL 4 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input RTL 5 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input SBS6 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input RTL 7 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Veronica HD / Disney XD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Net5 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input RTL 8 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input FOX HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input RTL Z HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Ziggo TV HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Ziggo Sport HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Comedy Central HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Spike HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Discovery HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input National Geographic Channel HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input SBS9 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Eurosport 1 HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input TLC HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input BBC First HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input MTV HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input 24Kitchen HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input XITE HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input VICEtv HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Disney Channel HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input HISTORY HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Nickelodeon HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input TV West
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Infothuis
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Lokale Omroep
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Lokale Omroep
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Lokale Omroep
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Lokale Omroep
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Lokale Omroep
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input ONS
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input één HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Canvas HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Ketnet
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input ARD HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input ZDF HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input WDR
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input NDR
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input RTL
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Sat. 1
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input BBC One HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input BBC Two HD
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input BBC Entertainment
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input TV5 Monde
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Play Store
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: YouTube
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Album
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Music
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Programme Guide
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Recorded Title List
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: TED
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Prime Video
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Play Music
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Play Games
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Play Movies &amp; TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Added input Netflix
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: BRAVIA Tutorials
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Video
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Help
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Sony Select
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Timers
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Internet Browser
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Screen mirroring
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Haystack TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Plex
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Pathé Thuis
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Rakuten TV: Jouw Bioscoop In Huis
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Regio TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Digital Concert Hall
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Rakuten TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Regio TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: Meteonews TV
[Homebridge] [1/29/2020, 22:00:44] [BraviaPlatform] Ignoring application: DW for Smart TV
[Homebridge] [1/29/2020, 22:00:45] [BraviaPlatform] Initializing platform accessory "TV".

**Comment by mmax-nl** [comment]
The multiple devices in the tile corresponds to the TV item for all the TV channels, and one item for each application. When enabling also Plex app, a new item appeared within the group called Plex. So potentially one can display the different items as separate tiles in HomeKit, cool.

**Comment by normen** [comment]
Yeah, this is a part of the "slow update" across HomeKit, TV channels appearing as separate devices with no controls for a while. They disappear once HomeKit gets its act together. This often happens when they get removed for come reason (e.g. CEC devices).

**Comment by dg1yds** [comment]
For me the behavior looks strange.
I tested with a clean homebridge and plugin installation - for the first start up time the channels are listed in the log window and appear in the Home-App in iOS as expected.
The channel can be switched - everything fine.

I reboot the homebridge server, the channels are still listed in the log window at homebridge start up, but do not appear in iOS anymore as selectable input.
HDMI inputs and screen mirroring is always available as input.

**Comment by dg1yds** [comment]
Just tested: remove bridge from iOS, add again - channels are listed in the log window and appear in the Home-App in iOS as expected.

The restart of homebridge seems to lead to an error somewhere.

**Comment by dg1yds** [comment]
Sorry for the many posts and maybe it's just a coincidence, but perhaps I have identified a note within the startup log for a working and not working situation.
It is the time when the message "Initializing platform accessory" comes up.

-- start up log - no channel list
[2/1/2020, 7:38:21 PM] Homebridge is running on port 51824.
[2/1/2020, 8:05:47 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/1/2020, 8:05:47 PM] ---
[2/1/2020, 8:05:49 PM] Loaded plugin: homebridge-bravia
[2/1/2020, 8:05:49 PM] Registering platform 'homebridge-bravia.BraviaPlatform'
[2/1/2020, 8:05:49 PM] ---
[2/1/2020, 8:05:50 PM] Loaded plugin: homebridge-config-ui-x
[2/1/2020, 8:05:50 PM] Registering platform 'homebridge-config-ui-x.config'
[2/1/2020, 8:05:50 PM] ---
[2/1/2020, 8:05:50 PM] Loading 1 platforms...
[2/1/2020, 8:05:50 PM] [BraviaPlatform] Initializing BraviaPlatform platform...
[2/1/2020, 8:05:50 PM] Loading 0 accessories...
[2/1/2020, 8:05:51 PM] [BraviaPlatform] Added input HDMI 1
[2/1/2020, 8:05:51 PM] [BraviaPlatform] Added input HDMI 2
[2/1/2020, 8:05:51 PM] [BraviaPlatform] Added input HDMI 3
[2/1/2020, 8:05:51 PM] [BraviaPlatform] Added input HDMI 4/ARC
[2/1/2020, 8:05:51 PM] [BraviaPlatform] Initializing platform accessory 'Fernseher'...
Setup Payload:
X-HM://0023ISYWZC1BM
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
....                     
[2/1/2020, 8:05:52 PM] Homebridge is running on port 51824.
[2/1/2020, 8:05:52 PM] [BraviaPlatform] Added input Das Erste HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input ZDF HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input RTL HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input SAT.1 HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input ProSieben HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input kabel eins HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input RTLII HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input VOX HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input arte HD
[2/1/2020, 8:05:53 PM] [BraviaPlatform] Added input 3sat HD
[..]
[2/1/2020, 8:05:56 PM] [Config] Homebridge Config UI X v4.9.0 is listening on :: port 11809


-- start up log - channel list available
[2/1/2020, 8:10:27 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/1/2020, 8:10:27 PM] ---
[2/1/2020, 8:10:28 PM] Loaded plugin: homebridge-bravia
[2/1/2020, 8:10:28 PM] Registering platform 'homebridge-bravia.BraviaPlatform'
[2/1/2020, 8:10:28 PM] ---
[2/1/2020, 8:10:29 PM] Loaded plugin: homebridge-config-ui-x
[2/1/2020, 8:10:29 PM] Registering platform 'homebridge-config-ui-x.config'
[2/1/2020, 8:10:29 PM] ---
[2/1/2020, 8:10:29 PM] Loading 1 platforms...
[2/1/2020, 8:10:29 PM] [BraviaPlatform] Initializing BraviaPlatform platform...
[2/1/2020, 8:10:29 PM] Loading 0 accessories...
[2/1/2020, 8:10:29 PM] [BraviaPlatform] Added input HDMI 1
[2/1/2020, 8:10:29 PM] [BraviaPlatform] Added input HDMI 2
[2/1/2020, 8:10:29 PM] [BraviaPlatform] Added input HDMI 3
[2/1/2020, 8:10:29 PM] [BraviaPlatform] Added input HDMI 4/ARC
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input Das Erste HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input ZDF HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input RTL HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input SAT.1 HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input ProSieben HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input kabel eins HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input RTLII HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input VOX HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input arte HD
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Added input 3sat HD
[..]
[2/1/2020, 8:10:30 PM] [BraviaPlatform] Initializing platform accessory 'Fernseher'...
Setup Payload:
X-HM://0023ISYWZC1BM
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
....
[2/1/2020, 8:10:31 PM] Homebridge is running on port 51824.
[2/1/2020, 8:10:32 PM] [Config] Homebridge Config UI X v4.9.0 is listening on :: port 11809

**Comment by normen** [comment]
@dg1yds How does your config look like? For some reason the plugin seems to return an accessory list before the TV sent all channels, I can‘t reproduce that behavior at all.

**Comment by dg1yds** [comment]
My config looks very simple.

{
    "bridge": {
        "name": "Homebridge@2",
        "username": "-cut-",
        "port": 51824,
        "pin": "-cut-"
    },
    "description": "Homekit sub gateway to the world",
    "platforms": [
        {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "Fernseher",
                    "ip": "192.168.2.30",
                    "soundoutput": "speaker",
                    "cookiepath": "/homebridge/sonycookie",
                    "tvsource": "tv:dvbs",
                    "applications": false,
                    "sources": [
                        "extInput:hdmi"
                    ]
                }
            ]
        },

... followed by other platforms and accessories.

Installed plugins: Homebridge Bravia, Homebridge Http Switch, Homebridge Http Webhooks, Homebridge Unifi Occupancy Sensor, Homebridge Config UI X

**Comment by normen** [comment]
Can you try running config-ui-x in a separate thread (see its manual) or disabling it for a while? I had issues with that plugin running on the homebridge thread with large setups as it blocks homebridge for quite a while during boot.

**Comment by dg1yds** [comment]
I used homebridge without config-ui-x plugin before, but the issue was also present.
I am using two homebridge instances to minimize the impact at start up. Sometimes your plugin receives the channel list in time, sometimes not.

Perhaps you can check if the robustness at start up can be improved.

**Comment by normen** [comment]
Well if the request fails or stalls in the network then the plugin can't read the channels.. I could increase the timeout or things like that but at some point the request will be dropped.

But I want to move the plugin to a dynamic accessory model anyway, then it's basically irrelevant when the TV actually reports its channels, they will simply be listed as "unavailable" if the TV didn't answer yet.

**Comment by normen** [comment]
Did this behavior change in the latest version?

**Comment by mmax-nl** [comment]
03/05/2020, 11:06:43 Loaded plugin "homebridge-bravia".
03/05/2020, 11:06:43 Loaded plugin "homebridge-neato".
03/05/2020, 11:06:44 Loaded plugin "homebridge-withings-air-quality".
03/05/2020, 11:06:44 [BraviaPlatform] Creating new accessory for TV
03/05/2020, 11:06:44 [BraviaPlatform] New TV TV, will be queried for channels/apps and added to HomeKit
03/05/2020, 11:06:44 [BraviaPlatform] Need to authenticate with TV!
03/05/2020, 11:06:44 [BraviaPlatform] Please enter the PIN that appears on your TV at http://hoobs:8999
03/05/2020, 11:06:44 [BraviaPlatform] PIN entry web server listening
03/05/2020, 11:06:44 (node:4371) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
03/05/2020, 11:06:47 Bridge is running on port 51826.
03/05/2020, 11:06:57 [BraviaPlatform] Error loading sources for extInput:cec
03/05/2020, 11:06:58 [BraviaPlatform] Added input HDMI 1
03/05/2020, 11:06:58 [BraviaPlatform] Added input HDMI 2
03/05/2020, 11:06:58 [BraviaPlatform] Added input HDMI 3/ARC
03/05/2020, 11:06:58 [BraviaPlatform] Added input HDMI 4
03/05/2020, 11:06:58 [BraviaPlatform] Added input NPO 1 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input NPO 2 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input NPO 3 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input RTL 4 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input RTL 5 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input SBS6 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input RTL 7 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Veronica HD / Disney XD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Net5 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input RTL 8 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input FOX HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input RTL Z HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Ziggo TV HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Ziggo Sport HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Comedy Central HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Spike HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Discovery HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input National Geographic Channel HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input SBS9 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Eurosport 1 HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input TLC HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input BBC First HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input MTV HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input 24Kitchen HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input XITE HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input VICEtv HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Disney Channel HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input HISTORY HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Nickelodeon HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input TV West
03/05/2020, 11:06:58 [BraviaPlatform] Added input Infothuis
03/05/2020, 11:06:58 [BraviaPlatform] Added input Lokale Omroep
03/05/2020, 11:06:58 [BraviaPlatform] Added input Lokale Omroep
03/05/2020, 11:06:58 [BraviaPlatform] Added input Lokale Omroep
03/05/2020, 11:06:58 [BraviaPlatform] Added input Lokale Omroep
03/05/2020, 11:06:58 [BraviaPlatform] Added input Lokale Omroep
03/05/2020, 11:06:58 [BraviaPlatform] Added input ONS
03/05/2020, 11:06:58 [BraviaPlatform] Added input één HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Canvas HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input Ketnet
03/05/2020, 11:06:58 [BraviaPlatform] Added input ARD HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input ZDF HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input WDR
03/05/2020, 11:06:58 [BraviaPlatform] Added input NDR
03/05/2020, 11:06:58 [BraviaPlatform] Added input RTL
03/05/2020, 11:06:58 [BraviaPlatform] Added input Sat. 1
03/05/2020, 11:06:58 [BraviaPlatform] Added input BBC One HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input BBC Two HD
03/05/2020, 11:06:58 [BraviaPlatform] Added input BBC Entertainment
03/05/2020, 11:06:58 [BraviaPlatform] Added input TV5 Monde
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Play Store
03/05/2020, 11:07:00 [BraviaPlatform] Added input YouTube
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Album
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Music
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: TV
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Programme Guide
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Recorded Title List
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: TED
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Prime Video
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Play Music
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Play Games
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Play Movies &amp; TV
03/05/2020, 11:07:00 [BraviaPlatform] Added input Netflix
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: BRAVIA Tutorials
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Video
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Help
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Sony Select
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Timers
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Internet Browser
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Screen mirroring
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Facebook Watch
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Haystack TV
03/05/2020, 11:07:00 [BraviaPlatform] Added input Plex
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Pathé Thuis
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Rakuten TV: Jouw Bioscoop In Huis
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Digital Concert Hall
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Rakuten TV
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Regio TV
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: Meteonews TV
03/05/2020, 11:07:00 [BraviaPlatform] Ignoring application: DW for Smart TV
03/05/2020, 11:07:00 [BraviaPlatform] Registering HomeBridge Accessory for TV
03/05/2020, 11:07:01 HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by mmax-nl** [comment]
I authenticated the TV, but still get the CEC error in the log,. Bravia plugin is 2.0.2 and HOOBS is 3.2.3

**Comment by normen** [comment]
I changed the output of the log, you won't have an "Error" anymore ;) I guess your TV simply doesn't support CEC, you can get rid of the message by setting an input source list without the cec entry - or just ignore it.

**Comment by mmax-nl** [comment]
My Sony TV support CEC. As a matter of fact the entire system is turned on/off by the Apple TV remote.

**Comment by mmax-nl** [comment]
![image](https://user-images.githubusercontent.com/58346648/81090008-69231b80-8efd-11ea-841b-d30502deec87.jpg)
![image](https://user-images.githubusercontent.com/58346648/81090083-7d671880-8efd-11ea-82ca-c6f916b39912.jpg)

**Comment by mmax-nl** [comment]
![image](https://user-images.githubusercontent.com/58346648/81090236-bacba600-8efd-11ea-8547-3de19ca39b0e.jpg)

**Comment by normen** [comment]
Okay, just find out the right identifier for the source of your TV then. A string like `tv:dvbt` or `extInput:cec` . Then add it to the source list.

**Comment by mmax-nl** [comment]
![3874580E-092E-4315-8B03-F2D67925A8A0](https://user-images.githubusercontent.com/58346648/81098753-17cd5900-8f0a-11ea-8aaa-d108ddc41d2f.png)

**Comment by mmax-nl** [comment]
![image](https://user-images.githubusercontent.com/58346648/81098987-772b6900-8f0a-11ea-8ebe-887f05889318.jpg)

**Comment by mmax-nl** [comment]
![image](https://user-images.githubusercontent.com/58346648/81099041-8ca09300-8f0a-11ea-9971-fef2933bbf17.jpg)
![image](https://user-images.githubusercontent.com/58346648/81099069-99bd8200-8f0a-11ea-8571-8280870bc2fb.jpg)

**Comment by mmax-nl** [comment]
So my tv is plugged via hdmi2 to a PS4 pro, via hdmi4 to an Apple TV 3 and via hdmi3 to a soundbar to which an UltraHD Blu-ray player and an Apple TV 4K are plugged via hdmi.

In the TV tile of Home app I see the 4 HDMI “channels”, but if I select for example HDMI2 or HDMI4 the devices are not powered on.

**Comment by normen** [comment]
Again, `extInput:cec` won't work on your TV. Find the right string for your TV. Then best make a wiki page here and put it down there.

**Comment by normen** [comment]
Closing this, if the channel synchronization issue should up again it will look completely different due to how 2.0+ registers channels differently.
