### ISSUE TITLE
Error writing cookie file to undefined

### ISSUE THREAD

**Issue by dxdr** [normen/homebridge-bravia#37]
Installed the plug-in, but when using systemd to launch homebridge get the following error in the log:

Apr  7 13:49:38 raspberrypi homebridge[1403]: [2019-4-7 13:49:38] [BraviaPlatform] Error writing cookie file to undefined. Add a cookiepath parameter to config.json to specify the path. Note that you specify the FILE path, not the folder.

Launching from the terminal works fine (creates a sonycookie file) ... There is no sonycookie folder anywhere in the system.  Tried specifying a path to /var/homebridge/sonycookie and taking that specifier out and no success.

Using 

{
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "TV",
                    "ip": "192.168.7.30"
                }
            ]

in my config... also tried adding a specifier:

 {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "TV",
                    "ip": "192.168.7.30",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbs",
                    "applications": false,
                    "cookiePath":"/var/homebridge/sonycookie",
                    "sources": [
                        "extInput:hdmi",
                        "extInput:component",
                        "extInput:scart",
                        "extInput:cec",
                        "extInput:widi"
                    ]
                }
            ]
        },

**Comment by normen** [comment]
Well you didn't specify `cookiepath`, you specified cookie**P**ath.

Edit: And it's a FILE name, there should be no folder with the name sonycookie, the plugin will create a FILE with that name you specify.

**Comment by dxdr** [comment]
Thank you, it was the capital P that was the error.
