### ISSUE TITLE
Add option to switch inputs

### ISSUE THREAD

**Issue by normen** [normen/homebridge-bravia#4]
Switching the input (HDMI 1/2/3, AV1 etc.) could be allowed via a custom parameter or some switches.

Note however that the better solution is to control HDMI-connected devices directly instead. The TV should recognize the HDMI source being turned on via CEC or other means and switch the HDMI port automatically.

For example I use "ps4-waker" via a command line switch in HomeKit for my PS4 and the TV switches the channel accordingly when the PS4 is turned on.

**Comment by iamdeeff** [comment]
Yes please! 😍

**Comment by normen** [comment]
Ties in with #34
