### ISSUE TITLE
No channel or volume control

### ISSUE THREAD

**Issue by benzman81** [normen/homebridge-bravia#41]
Hi, in apples Home App I can only turn tv on/off and switch Source Inputs. I am fully missing my channels and a way to control the volume. The TV is also not added to Apple Remote App. In homebridge log I can see that channels are being added and there are no errors.
Any hint how I can fix this?

**Comment by benzman81** [comment]
Just an addition: The TV is not added to Apple Remote App, but is selectable via iOS configuration screen. Weird. But Channels still not visible anywhere.

**Comment by normen** [comment]
I guess your iOS device didn't completely sync the new HomeKit configuration. Make sure you reboot your iOS device and any HomeKit bridge devices (Apple TV / HomePod). That should also fix the issue with the remote not appearing on the phone. I had such issues when adding new iOS devices to the home as well.

**Comment by benzman81** [comment]
Still no luck. Restarted apple tv, all three homepods and did a hard reset on my iphone. Still no channels and not available in Remote App.

**Comment by normen** [comment]
Well post here if you find the issue. HomeKit is funny that way. Adding the TV with a different name might help (via config json, not by just renaming it in homekit, you can then rename it back to your old name).

**Comment by francescob** [comment]
I also have a problem with my tv not appearing in the iOS remote

**Comment by lvhe19880210** [comment]
I also have a problem  with my tv only appearing in configuration screen not appearing in the iOS remote，have restarted all HomeKit bridge devicesand my ios device

**Comment by lvhe19880210** [comment]
> Well post here if you find the issue. HomeKit is funny that way. Adding the TV with a different name might help (via config json, not by just renaming it in homekit, you can then rename it back to your old name).


I also have a problem with my tv only appearing in configuration screen not appearing in the iOS remote，have restarted all HomeKit bridge devicesand my ios device
--
