### ISSUE TITLE
"Error loading sources for extInput:cec" when more 3 or more CEC devices connected

### ISSUE THREAD

**Issue by Nordikk** [normen/homebridge-bravia#46]
When 3 or more CEC devices are connected, it won't load any CEC sources at all.
If only 2 CEC devices are connected, it works as expected.

> [2019-7-21 17:23:20] [BraviaPlatform] Added input HDMI 1/MHL
[2019-7-21 17:23:20] [BraviaPlatform] Added input HDMI 2
[2019-7-21 17:23:20] [BraviaPlatform] Added input HDMI 3
[2019-7-21 17:23:20] [BraviaPlatform] Added input HDMI 4/ARC
[2019-7-21 17:23:21] [BraviaPlatform] Initializing platform accessory 'Fernseher'...
[2019-7-21 17:23:21] [BraviaPlatform] Error loading sources for extInput:cec

**Comment by normen** [comment]
Hm, I have 4 CEC devices, two are on one HDMI input even.. The error message doesn't have a stack trace does it? That indicates the TV simply sent an error back for some reason.

Although.. I do have an exceptionally bad way of checking for errors which is checking for the word "error" in the whole HTTP result of the TV 😅 Is any of your HDMI inputs called "Terror TV" or something? 😁

**Comment by Nordikk** [comment]
Nope, no stack trace :/

And no, none of my inputs is called like that 😂

**Comment by mmax-nl** [comment]
My KD-65XE9005 is connected via HDMI 3/ARC to an AVR Sony STR-DH790 to which a PS4, a Sony UHD Blu-ray player, an ATV 4 and an ATV 4k are also connected. However if I put in the config the cec I also get in the log the error message and no CEC input shows.

**Comment by normen** [comment]
My guess this is because it takes longer to get the CEC inputs because the TV is actually checking if something is connected on the HDMI ports when that request comes in.. Might be that in combination with a long boot due to other plugins the request simply gets lost.

This might tie in with https://github.com/normen/homebridge-bravia/issues/36# (see bottom)

**Comment by normen** [comment]
Is this still the case in 2.0?

**Comment by mmax-nl** [comment]
Yes, still the case.

**Comment by normen** [comment]
> Yes, still the case.

Did it actually work at all for you at some point? Note OP describes an issue where he can see a few devices. For you it rather sound like theres no CEC support in your TV

**Comment by mmax-nl** [comment]
I have never tried to "unplug" my other CEC devices to verify if it works with just 2 of them. I'll try later today as soon as my family stop watching TV :)

PS: in the meanwhile I changed my setup.
My KD-65XE9005 is connected via HDMI 3/ARC to an Samsung Soundbar Q90R to which a Sony PS4 and an Apple ATV 4k are also connected, and via HDMI 1 and 2 to a Sony UHD Blu-ray player, and an Apple ATV 4 .

**Comment by normen** [comment]
The latest version 2.0.3 gives a little more log output when this happens, maybe you could post here if you get any additional info.

**Comment by Nordikk** [comment]
It actually works for me in v2

**Comment by normen** [comment]
Cool, closing this then
