### ISSUE TITLE
Automation issue with ios13

### ISSUE THREAD

**Issue by pierrebuet** [normen/homebridge-bravia#48]
I'm using the switch of the plugin in an automation to switch a lamp off an on. Now with ios13 the automation is only working correctly when switching the TV on, but not anymore when switching it off. No matter if I use the switch in the home app (which switch the TV on and off correctly) or if I switch the TV with the remote control. 

I double checked my automation and doesn't see any chances there, I'm still listening for a deactivation of the TV switch. The only parameter that changed in the mean time since I got this strange behavior is ios13. Could it one that the status/setting for a switch changed there?

**Comment by normen** [comment]
Yeah, I am seeing issues with iOS13 and the power state as well, funny thing is only my phone is updated but the whole HomeKit ecosystem (HomePods, AppleTV, iPad) has that issue now..
