### ISSUE TITLE
WOL not working with Sony KD55AG9

### ISSUE THREAD

**Issue by stich86** [normen/homebridge-bravia#49]
Hi,

i've setup the plugin to command my new AG9. I can switch various channels and power off, but not power on.
MAC was put into the config and allow remote control is enabled on the TV but not work :(

Any hints?

Thanks!

**Comment by QandnotU** [comment]
@stich86 looks like Sony released native HomeKit and Airplay Support for that model today.

**Comment by stich86** [comment]
Stilo not for mi model, online for US one :(

**Comment by normen** [comment]
Did you try it without the MAC address? It's only needed if you specifically want to use WOL. It's usually not needed to turn on the TV.
