### ISSUE TITLE
Detect app/channel status to trigger automations

### ISSUE THREAD

**Issue by rogerveijk** [normen/homebridge-bravia#50]
Feature request to detect app/channel status to trigger automations.

E.g. Netflix app is open (or plays content) trigger a automation (example dim hue lights).

Best would be to only create a motion sensor for a specific app/channel, since regular tv channels for example shouldn’t tigger anything in my situation.

The benefit of adding a motion sensor is your automations will even be triggered when the tv is controlled by a regular remote (instead of by Siri).

**Comment by normen** [comment]
I doubt I will add that function, seems unnecessarily complicated as well as you'd have to configure it in the config.json. I (as I suppose many others too) simply have a HomeKit scene that sets the lighting and turns on NetFlix when I say "Hey Siri, Netflix Time".
