### ISSUE TITLE
problem with my TV

### ISSUE THREAD

**Issue by symphil** [normen/homebridge-bravia#55]
Hi Normen

Good day
Just want to share the problem I have, and seeking a solution.
TV KD-55A9F
1. some TV app can not show in homekit, even I add it in config.

2. no idea how to set volume. downloaded Apple TV remote app, but it only show my Apple TV 4K

hope this plugin will be better and better 

Thanks for your help.

Phil

This issue tracker is ONLY for BUG REPORTS with proper error descriptions, instructions for recreating the bug, message logs and hard- and software descriptions.

Please understand that this is NOT a support forum, there IS NO SUPPORT for this free software outside of the manual. Requests for help or support WILL be closed without answer.

**Comment by normen** [comment]
1) The TV might use a different name internally, check the homebridge log
2) Use the built-in remote of iOS 12.2+

**Comment by symphil** [comment]
Dear Normen

Thanks for your reply. 
the remote on iPhone is OK now.
but the APP still a problem. 
there are some app can not show, and even can not find in the homebridge log, can you check what is the problem?
Thanks
Phil Yao
