### ISSUE TITLE
readme.md missing cookie step

### ISSUE THREAD

**Issue by drbenschmidt** [normen/homebridge-bravia#58]
I just setup this plugin and had to debug where the `sonycookie` file was attempting to be created. Since I'm running homebridge as a service, the default cookie path was invalid and was throwing an error (would be nice if those were logged, even just as `JSON.stringify`)

Anyway, the path it was looking for was `/home/homebridge/.homebridge/sonycookie`, that could help someone out in the future.

Thanks!

**Comment by normen** [comment]
As described in the README: https://github.com/normen/homebridge-bravia#configure-configjson
