### ISSUE TITLE
Only one TV showing up in the remote app

### ISSUE THREAD

**Issue by Cheetah471** [normen/homebridge-bravia#60]
Hey,
Thank you for this plugin.
I have two Sony TV’s. And only one of them shows up in the remote app. Sometimes it’s the first one, sometimes it’s the second one. Everything else works perfectly
I also have an Apple TV, I don’t know if it’s the cause of this problem
[Screenshot](https://user-images.githubusercontent.com/24874742/79080712-dfc66200-7d1f-11ea-87c8-25e876d09987.png)

**Comment by normen** [comment]
The remote app functionality seems to be a bit flakey in general, I don't always see the TV listed either. I don't know if thats because of HomeKit, homebridge or the plugin though. There isn't really any code for that, it basically happens "automagically" if your plugin publishes a TV that has the appropriate buttons so I don't know exactly what to do about this.

**Comment by lesliedu** [comment]
I also found this issue, I guess it is caused by the different wireless router, you must have two or more wireless router or mesh AP with same SSID in your place. if you on the same network of the TV, the one will be shown in the remote screen. @normen @Cheetah471

**Comment by Cheetah471** [comment]
@lesliedu Could be the issue because I have 3 AP’s with same SSID’s. But even when I’m connected to the same AP as TV1 I’m still only seeing TV2 in remote app

**Comment by normen** [comment]
please check if this still happens in 2.0, you will have to reconfigure your Tv though

**Comment by Cheetah471** [comment]
The issue is still there, even on the newest version

**Comment by normen** [comment]
Then I am out of ideas. Unless I am missing some flag everything should have its separate name and such, others also have multiple TVs running.. It could be a network thing as others said.

**Comment by sercontri** [comment]
Hello everyone... I also have 2 Sony Bravia Tv of 2015 with Android TV 7 (last update) and neither of them appears to me in the remote app. I also do not know if the volume can only be used from the remote app, from nowhere it works for me. I have homebridge (latest version) in Docker inside a Synology NAS and plugin 2.1.9.

**Comment by normen** [comment]
Apple has various "remote apps". The one that is in the contol center of the latest iOS versions (no app to install) should work with this.

https://support.apple.com/en-us/HT202769

**Comment by sercontri** [comment]
exact! once again I would never have noticed, when talking about the app I thought it was the one that was downloaded. It works perfectly for me. Thanks again for the work.

**Comment by normen** [comment]
There is one to download in the App Store that does work as well, I guess its for older iOS versions. Then theres one that doesn't - I guess its for the old iTunes connect way of controlling things.. Even Apple has some messy corners.

**Comment by sercontri** [comment]
I have tried that old one and no television detects me.  The one that has indicated me from the control center only detects a TV, but as indicated in other messages it can behave like this.  I will do tests because it seemed to me like I had to choose a TV within the remote "application" and when choosing one, he met the second TV in hombridge and that is not my opinion in the remote "application" available to be chosen.

**Comment by normen** [comment]
This seems to be a limitation for platform accessories, see #102

**Comment by myaccount99** [comment]
I have the same Problem here 2 Sony TVs all configured the same way in the plugin, but only one is showing up in the remote app (the one which is startet from the control center) 
Other from that the app is genius

**Comment by normen** [comment]
On Wed Jun 24, 2020 at 8:23 AM CEST, myaccount99 wrote:

> I have the same Problem here 2 Sony TVs all configured the same way in the plugin, but only one is showing up in the remote app (the one which is startet from the control center) 
> Other from that the app is genius 
Thanks, the source of the issue has been found though, no need to confirm it.
