### ISSUE TITLE
Exception!  TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ursusHU** [normen/homebridge-bravia#62]
I have a non Android Sony Bravia KDL-50W815B. If I install the plugin it works fine, but after Homebridge is restarted for some reason, I get the following error:

[Homebridge] [4/24/2020, 11:19:58 PM] [BraviaPlatform] Exception!  TypeError: Cannot read property '0' of undefined
    at onSucces (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:316:36)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-bravia/index.js:676:9)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by normen** [comment]
Nothing to worry about.

**Comment by ursusHU** [comment]
Thanks, well my TV "button" in Homekit stops to work, doesn't get the status from the TV, and also can't be controlled from Homekit anymore.

**Comment by normen** [comment]
Well how about you would have said that in the first place? So your TV doesn't seem to react to the messages anymore and sends bogus messages back, maybe your cookie file gets lost for some reason or something else is wrong with the authentication to the TV. Maybe you left the PIN in the config file, who knows. But as stated in the commit hint, thats all the hand-holding I can provide here.

**Comment by ursusHU** [comment]
Thank you for the clarification, as I wrote if I reinstall the plugin it works again. I don't think that's the fault is on the side of the TV in this case. PIN is not included in the config file. Have a nice day.
