### ISSUE TITLE
WOL does not work on Sony Bravia KD-65AG8

### ISSUE THREAD

**Issue by emeidi** [normen/homebridge-bravia#64]
My Sony Bravia KD-65AG8 running Android 8 can't be started using Wake-on-LAN (WOL). I have "Remote start" enabled.

I tried both with this plugin by specifying the "mac" attribute in the configuration, as well as the Unix tool wakeonlan both on macOS 10.13 (0.41 through MacPorts) and Debian GNU/Linux 9.12 (0.41 as well).

If your TV can't be turned on through WOL, make sure you **DO NOT** add the "mac" attribute to your configuration, since the code then automatically switches to WOL. Once you remove the "mac" attribute, the plugin will try to start the TV using the TV's server. This is when this function started to work for me.

**Comment by normen** [comment]
Exactly, wither WOL or the internal method. "Remote Start" is not the same as WOL. WOL is a lowlevel network function.
