### ISSUE TITLE
Populating "pwd" with PSK won't work

### ISSUE THREAD

**Issue by emeidi** [normen/homebridge-bravia#65]
I have set a pre-shared key (PSK) on my Sony Bravia KD-65AG8.

Although I provided this PSK in the configuration with the attribute `pwd`, the plugin wasn't able to authenticate with the TV.

I ended up removing this attribute altogether.

Once I restarted homebridge, I got prompted for entering the PIN displayed on the TV. You have 50 seconds to do this, and in order to not too much pressure on you, it nicely counts down while you are rushing to add the pin to the configuration file (e.g. "pwd":"1234") and restart homebridge. After multiple attempts, I didn't arrive to make it within this short amount of time.

I restarted homebridge one final time, and although the debug messages kept filling up the screen after the prompt, I eventually decided to just enter the four numbers and to hit return. Homebridge accepted the input, and the plugin got authorised to talk to the TV.

**Comment by normen** [comment]
Basic password support is discontinued

**Comment by Soldiiier** [comment]
Hi,
 is there any method in the current release to get PSK authentication to work?
Thanks

**Comment by normen** [comment]
No
