### ISSUE TITLE
events.js:160 throw er;

### ISSUE THREAD

**Issue by magefesa** [normen/homebridge-bravia#7]
On my Sony Bravia, I can run and enter the pin, but than alway throw an error  

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '_directory of cookiePAth_'
    at Error (native)

I ve add another directory with CookiePAth parameter but no results...any ideas pleasE?

**Comment by normen** [comment]
Its not a directory name, its a file name.

**Comment by magefesa** [comment]
So...To solve it? Please?

**Comment by magefesa** [comment]
I d'on t know how to avoid that error, please could you explain me what i haver to do?

**Comment by normen** [comment]
Point to a non-existing file in an existing directory. Say if you made the directory "/home/pi/mystuff/" you enter "cookiepath": "/home/pi/mystuff/cookie.file"

What you did is create the directory and then enter "cookiepath": "/home/pi/mystuff"

**Comment by magefesa** [comment]
On json file i ve added The "cookiepath" parAmeter:

"cookiepath":"my_folder"

My_folder can be any existing path ? 

I ve done this and the error persist

**Comment by normen** [comment]
File, not folder.

You don't have to enter the folder name, you enter a file name.

The path you enter denotes the path to a file and not a folder.

Don't enter the folder name, enter the file name.

The parameter is not a folder name, its a file name.

Cookiepath is a file name, not a folder name.

**Comment by magefesa** [comment]
Ok!
I ll try later!!
Sorry !!
"cookiepath":"/folder name/cookie.file"

Right?

**Comment by normen** [comment]
Yes :)

**Comment by magefesa** [comment]
All works like a charm!!!

Thanks a lot !!! 
Now from ElGato i can control volumen, channel...

Not from Home, but enough!!

**Comment by normen** [comment]
Read the manual, you can create scenes in Elgato Eve that you can use in Home and with Siri.

**Comment by magefesa** [comment]
Volume/ on-off working fine

Channel does not works....Ideas?

**Comment by normen** [comment]
Read. The. Manual. Create a scene in Elgato with Channel = 1 and call it "Turn on channel one", the scene will work in Home and Siri.
