### ISSUE TITLE
Cannot add a Service with the same UUID

### ISSUE THREAD

**Issue by kkulesa** [normen/homebridge-bravia#72]
Hi, there is an issue for Vectra TV provider (about 1 million subscribers in Poland).
There is "Vectra Info" channel which makes a problem related to the same UUID.
Could you please ignore such issue and skip channel instead of throwing an error? 

maj 04 14:07:07 raspberrypi homebridge[21451]: [2020-5-4 14:07:07] Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'tv:dvbt?trip=100.110.10009&srvName=Vectra Info' as another Service in this Accessory.
maj 04 14:07:07 raspberrypi homebridge[21451]:     at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:282:17)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at /usr/local/lib/node_modules/homebridge-bravia/index.js:245:20
maj 04 14:07:07 raspberrypi homebridge[21451]:     at Array.forEach (<anonymous>)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at SonyTV.registerAccessory (/usr/local/lib/node_modules/homebridge-bravia/index.js:244:17)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at onSucces (/usr/local/lib/node_modules/homebridge-bravia/index.js:338:10)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia/index.js:732:9)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at IncomingMessage.emit (events.js:322:22)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at endReadableNT (_stream_readable.js:1187:12)
maj 04 14:07:07 raspberrypi homebridge[21451]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by normen** [comment]
It's not an issue with the channel or the provider or the country you live in, you simply have that channel stored twice in your TV, remove one of them.
