### ISSUE TITLE
Channel list and audio controls fail to load. Only inputs are showing. 

### ISSUE THREAD

**Issue by heller10** [normen/homebridge-bravia#73]
Everything works fine registering the TV, but it fails to download any channels or audio controls. It only shows the inputs and power on/off.

**Comment by normen** [comment]
I have a piece of string in my hand. How long is it?

**Comment by heller10** [comment]
[BraviaPlatform] Creating new accessory for Living Room TV
5/4/2020, 2:43:24 AM [BraviaPlatform] New TV Living Room TV, will be queried for channels/apps and added to HomeKit
5/4/2020, 2:43:25 AM [BraviaPlatform] Added input HDMI 1
5/4/2020, 2:43:25 AM [BraviaPlatform] Added input HDMI 2
5/4/2020, 2:43:25 AM [BraviaPlatform] Added input HDMI 3/ARC
5/4/2020, 2:43:25 AM [BraviaPlatform] Added input HDMI 4
5/4/2020, 2:43:25 AM [BraviaPlatform] Error loading sources for extInput:component
5/4/2020, 2:43:25 AM [BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}
5/4/2020, 2:43:26 AM [BraviaPlatform] Error loading sources for extInput:scart
5/4/2020, 2:43:26 AM [BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}
5/4/2020, 2:43:26 AM [BraviaPlatform] Added input DISH Hopper
5/4/2020, 2:43:26 AM [BraviaPlatform] Added input Living Room
5/4/2020, 2:43:26 AM [BraviaPlatform] Added input HT-Z9F
5/4/2020, 2:43:26 AM [BraviaPlatform] Added input HT-Z9F
5/4/2020, 2:43:26 AM [Ring] Creating location socket.io connection
5/4/2020, 2:43:26 AM [BraviaPlatform] Added input Screen mirroring
5/4/2020, 2:43:27 AM [BraviaPlatform] Error loading sources for tv:dvbs
5/4/2020, 2:43:27 AM [BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}
5/4/2020, 2:43:27 AM [BraviaPlatform] Registering HomeBridge Accessory for Living Room TV

Here is the log which hopefully helps

**Comment by normen** [comment]
It tells me that your TV doesn't have component, scart or satellite (dvbs) inputs. Maybe your TV is cable (dvbc)? Anyway closing this as theres no error in the plugin.

**Comment by heller10** [comment]
Wow, you’re quite pleasant to deal with...maybe I posted it incorrectly or in the wrong spot, but I was just trying to share that none of the channels were being shown from the scan (shows it failed), and there are no audio controls. I was under the impression that the plugin was intended to create these things.

**Comment by normen** [comment]
Please read the manual. The plugin behaves as expected, there is nothing I can do in code. I _clearly_ state that there is no user support here. I gave you a hint about dvbs vs dbc, maybe you look into that? I guess you simply have cable TV instead of sat TV.
