### ISSUE TITLE
WOL Broadcast address

### ISSUE THREAD

**Issue by AQPSal** [normen/homebridge-bravia#79]
Please add an option to change the broadcast address for WOL. My TV is in a separate vlan. Default of 255.255.255.255 does not work across vlans. 

 wol.wake(this.mac, **{ address: "x.x.x.x" },** onWol);

This works for me when I modify your code. 

This is a great plugin. Thank you for the fantastic work!

Apologies if this is not the right way to make a request. I am new to coding and github.

**Comment by normen** [comment]
Really only super old TVs need WOL, doesn't it work without?

**Comment by normen** [comment]
Looking at the code best make that whole output optional and maybe you want to activate the online/offline callbacks as well to get even more info?

**Comment by AQPSal** [comment]
> Really only super old TVs need WOL, doesn't it work without?

My TV is a 2013 model - XBR65X900A. I can use the official Sony remote app only when in the same vlan, but it will not work if my phone is connected to the vlan where the homebridge server is connected. WOL works well; I use the router to pass packets across vlans using an specific broadcast address, rather than the default broadcast address. 

I have a “secure vlan”, an IOT vlan for TVs, chromecast, and such, and an “untrusted iot vlan” for plugs, switches. The design is security minded, which I expect more and more people would/should consider for their home network given the proliferation of security breaches in iot devices.

**Comment by normen** [comment]
Okay, tell me if it works.

**Comment by AQPSal** [comment]
Sorry if I wasn't clear - it does not work with my setup. WOL works perfectly except for the broadcast address. Thanks.

**Comment by normen** [comment]
> Sorry if I wasn't clear - it does not work with my setup. WOL works perfectly except for the broadcast address. Thanks.

No, I mean tell me if the new WOL address feature I just added works, add woladdress to config.json

**Comment by normen** [comment]
Sorry, the `npm publish` command got hung up somewhere, 2.1.3 should be out now, adding the `woladdress` parameter.

**Comment by AQPSal** [comment]
Works perfectly! thanks!
