### ISSUE TITLE
“channelupdaterate”: false not working

### ISSUE THREAD

**Issue by benjaminbogdanovic** [normen/homebridge-bravia#84]
When my Apple TV turns on, it renames the HDMI input to “Living Room Apple TV”. This input gets picked up by the plugin and adds it as a new input. When the Apple TV turns off, it removes the input. This would be fine, but it moves the TV tile in the Home app to the bottom every time this update/remove process happens. I imagine this happens whenever an input/channel is added/removed. As I do not see my inputs/channels changing often, I set channelupdaterate to false, but it seems not to be stopping the input being added or removed. Any suggestions would be appreciated.

![image](https://user-images.githubusercontent.com/16837687/81481861-e8c92700-922a-11ea-91f2-752ffb7dd9e5.jpeg)

**Comment by normen** [comment]
Hm, can you try setting it to `0` please?

**Comment by benjaminbogdanovic** [comment]
Still doing the same thing.

In regard to the tile on the Home app going to the bottom, force closing it and reopening puts it back where is was before, but to update the control centre tiles, restarting the phone is needed.

**Comment by normen** [comment]
What exactly is "the thing". If you mean it scans the inputs on each boot then that is expected. What would be unexpected is the inputs being coniunously updated every 30 seconds. Also, what node version are you running this on?

The HomeKit isse itself is a copy of #74 and #76 - this is specifically about the behavior of `channelupdaterate`

**Comment by benjaminbogdanovic** [comment]
Apologies for the lack of clarity. The “thing” is that it is still updating even though channelupdaterate is set to false/0.

Node version 12.16.1

**Comment by normen** [comment]
Okay, setting false or 0 should work now.
