### ISSUE TITLE
hombridge version is not supportet

### ISSUE THREAD

**Issue by knylbyte** [normen/homebridge-bravia#86]
> The plugin "homebridge-bravia-tv" requires a Homebridge version of ^0.4.38 which does not satisfy the current Homebridge version of 1.0.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

hey your plugin needs an update because the current version of homebridge is not supported.

**Comment by normen** [comment]
That is not my plugin

**Comment by knylbyte** [comment]
oh sorry
