### ISSUE TITLE
Can't load sources for extInput:scart

### ISSUE THREAD

**Issue by mkormendy** [normen/homebridge-bravia#87]
I'm seeing the following error repeatedly every 5 seconds or so in the logs:

```
[BraviaPlatform] Can't load sources for extInput:scart
[BraviaPlatform] TV response:
[BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}
```
I don't know what scart is, how do I stop this from showing up in the logs?

**Comment by normen** [comment]
Apparently your TV has no SCART input.

**Comment by mkormendy** [comment]
Great, how do I stop it from reporting that in the logs.

**Comment by normen** [comment]
Check the manual about the default sources.

**Comment by mkormendy** [comment]
Wow. Okay.
