### ISSUE TITLE
Home App required to be forced closed to show inputs 

### ISSUE THREAD

**Issue by Soldiiier** [normen/homebridge-bravia#88]
Great effort on this plugin. 

I was able to configure my source inputs only be hdmi or cec (or both), however when turning the tv off/standby those inputs get wiped away. Until the TV is back turned on. 
I can see the HB logs showing that there are inputs being removed (upon turn off) and inputs are added (upon turning on). 
But in order to have some meaningful/accurate sources displayed in home.app you need to force close the app on each power transition. 
Is it necessary for the plugin to remove the inputs when in standby?

**Comment by normen** [comment]
Copy of #74

**Comment by normen** [comment]
Okay, in version 2.1.10 the TV power state is checked before scanning channels. Most TVs support scanning the channels while the TV is off - some apparently don't. That doesn't solve the HomeKit display issue but thats out of the scope of the plugin anyway.

**Comment by Soldiiier** [comment]
Nice solution! 👏🏼👏🏼
