### ISSUE TITLE
renaming inputs in homekit does not stick after homebridge restart

### ISSUE THREAD

**Issue by itsermo** [normen/homebridge-bravia#89]
i would like to rename my inputs for example:

HDMI1 -> AppleTV
HDMI2 -> PlayStation 4

etc.

I can do this in HomeKit app, and it works, so long as homebridge is running.  However, this change does not stick around after homebridge restart.

Is there a way to make this change stick? Either via HomeKit or config.json for Homebridge?

**Comment by normen** [comment]
Really, renaming is more of a feature creep, I didn't find a way to disable the HomeKit built-in functionality. If you have more info about the topic or an example of a plugin where it works or even want to add the feature yourself I'm all ears.

As of now to make it stick either rename the inputs in your TV (if possible) or use the CEC assigned inputs, which should basically be the HDMI inputs with their own reported names.

**Comment by normen** [comment]
Wait, are you sure that the devices haven't just been re-added? Please check the log if theres messages about the devices being added or removed when that happens. I really don't know why HomeKit would lose those names, I don't touch them in the plugin once they're added.
