### ISSUE TITLE
Error id13 in every 5 seconds

### ISSUE THREAD

**Issue by DaneeF** [normen/homebridge-bravia#9]
Hello,
i got `Error?  {"error":[3,"source is invalid"],"id":13}` in every 5 seconds after the homebridge starts running. 
If i turn the TV off with Siri or through the Home app the `Error?  {"error":[7,"not power-on"],"id":13}
` error messages shows up. 

My config.js looks like this: 
`
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
"platforms":[
  {
    "platform": "BraviaPlatform",
    "tvs": [
      {
        "name": "Sony TV",
        "ip": "192.168.1.36",
        "tvsource": "tv:dvbs",
        "soundoutput": "speaker",
        "maxchannels": 100,
        "listapplications": 0
        }
]
}
]
}
`

Could you please help me solve this problem? 
Thanks!

**Comment by jameskirsop** [comment]
@DaneeF, did you come up with a solution to this problem? I'm having a similar issue.
