### ISSUE TITLE
Device can't be accessed after update to 2.2

### ISSUE THREAD

**Issue by LeJeko** [normen/homebridge-bravia#91]
It is not really an issue but rather a way of doing things.
As you know following my last issue, the other day I updated my homebridge instance (1.0.4) as well as recreating my Bravia accessory (2.1.11).

Today, new version of the plugin (2.2.1) I update.
Although my accessory remains in the Home app, it becomes inactive again, like an orphan.

Apparently the modifications made in version 2.2.0 concerning the "clientid" (index.js line: 222) are the cause of the problem because the way of generating the identifier to be checked has changed.
I had to delete it and recreate it.

Good news on the other hand, I have again the display of the current channel which is correct in the icon of the accessory! Perfect.

**Comment by normen** [comment]
I see. Thanks for reporting. I guess you mean the actual TV accessory, not the single "channels as accessories" HomeKit sometimes leaves. I tested it on my setup and it worked without recreating, I guess that won't be the case for everybody - especially those that already recreated the TV after (I think) 2.1.9. But the other good news is that you now have an even more secure connection to your TV :)
