### ISSUE TITLE
Speakers 

### ISSUE THREAD

**Issue by ghost** [normen/homebridge-bravia#92]
Hello, 

Thx for the great platform. It is not really an issue but what do you mean with headphones? I use 5.1 system and if i‘m starting the tv via home app I can happened the also the speaker on the tv will appear.

**Comment by normen** [comment]
I don't mean anything by that, its something the TV expects when you send a command to control the volume. If you can control the volume and mute then you don't need to change anything.

**Comment by ghost** [comment]
Hello,

That means I can delete this command in the config file because otherwise I have an kind of echo. If I mute the TV via controller, it will mude TV speakers and 5.1 system

**Comment by normen** [comment]
Please, this is where you help me, not the other way around. Please check what your TV does, write it up in a nice way and post it here so others who have the same issue will know what to do.
