### ISSUE TITLE
Missing inputs in selection list

### ISSUE THREAD

**Issue by alexgarden** [normen/homebridge-bravia#93]
Great plugin!

On previous versions, omitting the "sources" tag caused the plugin to add the defaults, and enumerating them caused only the enumerated sources to show up in the accessory.  This is expected.

I was running a sources list of [] to keep the selector blank but now I need to enumerate "extInput:HDMI1, extInput:HDMI2".  Unfortunately, neither eliminating "sources" for the default list or enumerating as above causes any chance to the list of sources in the accessory.  Has something changed or am I doing something wrong?

Thanks!

**Comment by normen** [comment]
Nothing really changed about this, the format would be `sources: ["extInput:HDMI1","extInput:HDMI2"]`, I guess these are case sensitive though, the defaults include a lowercase `extInput:hdmi`.

Edit: really, all hdmi inputs should be included in `extInput:hdmi`, I doubt there is hdmi1 or hdmi2

**Comment by alexgarden** [comment]
Super strange.  That's precisely the text I have.  Here's my config snippet:

"tvs": [
                {
                    "name": "Family Room TV",
                    "ip": "10.0.0.8",
                    "serverPort": 8999,
                    "sources": [
                        "extInput:HDMI1",
                        "extInput:HDMI1"
                    ]
                }
            ],
            "platform": "BraviaPlatform"

I swear though, even after multiple reboots, the TV accessory in HomeKit is not showing up any input selections.  I have other accessories which use that case, "HDMI1" and work so I believe that is the correct naming and case.

I did see a line in the startup log "[5/18/2020, 8:36:10 AM] [BraviaPlatform] Restoring Family Room TV from HomeKit"

Any chance this line implies that there is some stored HomeKit state that is fighting with the config?

.a


________________________________

**Comment by normen** [comment]
Did you try just `extInput:hdmi` as in the default? It's not single inputs, its the type of input.

**Comment by alexgarden** [comment]
Super strange.  I did another reset and all of a sudden it works.  Strange behavior, but in any event thank you very much for your quick responses.

.a

________________________________

**Comment by normen** [comment]
> Super strange. I did another reset and all of a sudden it works. 

What works now?

**Comment by alexgarden** [comment]
Apologies.  By "works", I mean the accessory is now shoing the enumerated inputs correctly.

**Comment by normen** [comment]
> Apologies. By "works", I mean the accessory is now shoing the enumerated inputs correctly.

Sorry, I mean what settings work now?

**Comment by alexgarden** [comment]
OK.  I think I know what's going on.  The TV accessory now enumerates four inputs:

  1.  HDMI 1
  2.  HDMI 2
  3.  HDMI 3/ARC
  4.  HDMI 4

Yesterday, the reason I was resetting the controller so much is that I swapped out my Yamaha reciever from a RX-S601 to a RX-V685.  The TV accessory seems to be enumerating the inputs on the Yamaha Receiver vs. itself.  Does this makes any sense to you?

.a

________________________________

**Comment by normen** [comment]
That looks like the normal list of HDMI inputs that is reported when a Sony TV is queried for `extInput:hdmi`.  If queried for `extInput:cec` most Sony TVs will report a list of names that the connected HDMI devices provide. I still think the issue was simply that you queried for `extInput:HDMI1` which is not an existing source list for the TV.

**Comment by alexgarden** [comment]
AAAH!  I am sorry... I thought that "extInput:hdmi" was an explicit reference to an input called "hdmi".  In fact, it's a reference to a class of inputs (in this case HDMI) which gets me that enumerated list.

If I'm right about this, I would encourage you to update the docs as it's not super clear.

Thank you!

.a

________________________________

**Comment by normen** [comment]
This is nothing I decided on. I don't _know_ if this is the case for all Sony TVs. All I found out is that you can query a Sony TVs "sources" and it will return a bunch of URIs that you can use to switch to those inputs.

**Comment by alexgarden** [comment]
Got it.  My point was only that in the documentation it seemed to me that the sources tag was there to enumerate sources but in fact, it's a switch asking for an enumeration of a class of sources.

________________________________

**Comment by normen** [comment]
Enumerating sources is the exact use of the array 😄 Using "source" in the way Sony uses the word. Afaict it can be a single physical input (like component) or a single physical input with multiple channels (dvb) or a type of input with multiple physical inputs (hdmi).

**Comment by alexgarden** [comment]
Roger.  May be worth a few lines in the readme.  Otherwise, thanks so much!

________________________________

**Comment by normen** [comment]
I'd rather have it that somebody actually researches this topic so there could be concise information about it instead of empirically gathered info.

**Comment by alexgarden** [comment]
Understood!
  

  
  
  

  
  
>
