### ISSUE TITLE
Applications not working

### ISSUE THREAD

**Issue by AtomicLight** [normen/homebridge-bravia#98]
Using the sample code to add applications does not work. I get invalid JSON.

**Comment by normen** [comment]
Activating my remote viewing abilites.. Looking through the code on your
computer... Checking logs.. Theres a `,` missing.

**Comment by AtomicLight** [comment]
Then the sample code is incorrect?

**Comment by normen** [comment]
Well, it depends on where in your config.json the code is added.

**Comment by AtomicLight** [comment]
Below is the full entry I am trying to use.

[
    {
        "name": "TV",
        "ip": "10.0.0.220",
        "applications": [ { "title": "tinyCam PRO" }, ],
        "Sources": [
            "extInput:hdmi1",
            "extInput:hdmi2",
            "extInput:hdmi3",
            "extInput:hdmi4"
        ]
    }
]

********

 If I remove

 `        "applications": [ { "title": "tinyCam PRO" }, ],
` it works great.

**Comment by normen** [comment]
Yeah, thats invalid JSON. Try this:

 "applications": [ { "title": "tinyCam PRO" } ],

 Also google JSON in general if you want to avoid inflicting further
 pain on yourself and others.

**Comment by normen** [comment]
oh and by the way those "sources" settings won't work either. They won't
give you an error but they won't do anything as "Sources" is written in
uppercase (wrong) and "extInput:hdmi1" is not a source type,
"extInput:hdmi" is and will give you all hdmi outputs.

But as said, this is not a support forum and there is no bug in the
software or documentation so I guess thats the last hint from me here.

**Comment by AtomicLight** [comment]
Thanks Normen. Appreciate it.
