### ISSUE TITLE
PIN authenticate keeps failing

### ISSUE THREAD

**Issue by rogerveijk** [normen/homebridge-bravia#99]
Error: Need to authenticate with TV! Please enter the PIN that appears on your TV at **adres**

The TV Displays the PIN screen. When i visit the by homebridge defined **adres**, i enter my pin and press submit it keeps loading till a time out.
When i directly paste **adres**/?pin=**PIN** in my browser,i do get the message "PIN **PIN** sent"
However, homebridge doesn't receive the pin / the TV keeps displaying the PIN screen.

When i set up a custom pin port, i get the message "PIN **PIN** sent" without any timeouts.
However, homebridge doesn't receive the pin / the TV keeps displaying the PIN screen.

I gave these folders Read, write, and execute permissions (sudo chmod -R 777)
/usr/local/lib/node_modules
~/.homebridge
~/.npm

Software versions:
homebridge-bravia v2.2.1
homebridge-config-ui-x v4.21.0
Node.js v14.3.0
Npm v6.14.5
OSX 10.15.15

TV (most recent software)
Model: Bravia 2015 
Version: 7.0
Kernel: 3.19.79 root@BuildHost153 #1 Fri Oct 19 01:32:19 JST 2018
Build:SVPDTV15_EU-user 7.0 NRD91N.S28 5.417 release-keys

With my Samsung TV's (also Pin setup) i don't have problems. Is there a way to fix this, or activate without pin?

**Comment by normen** [comment]
Theres no way to set up the TV without a PIN, no.

Don't know about your issue, maybe some firewall configuration? Another
server on the same machine? Did you try using a port above 10,000?

Also check this: https://support.apple.com/en-us/HT202944

**Comment by rogerveijk** [comment]
Resolved: In TV settings there was already granted acces to "homebridge", probable from a previous version. After removing in the TV setting, i set it up and it directly worked.
Thanks for the super fast reply anyway!

**Comment by normen** [comment]
Hm, funny really as the TV should register with a completely new ID, it
should just add the new item to that list. Anyway, glad your resolved your issue.
